item replace block ^-1 ^2 ^3 container.0 with minecraft:air
item replace block ^-1 ^2 ^3 container.1 with minecraft:air
item replace block ^-1 ^2 ^3 container.2 with minecraft:air
item replace block ^-1 ^2 ^3 container.3 with minecraft:air
item replace block ^-1 ^2 ^3 container.4 with minecraft:air
item replace block ^-1 ^2 ^3 container.5 with minecraft:air
item replace block ^-1 ^2 ^3 container.6 with minecraft:air
item replace block ^-1 ^2 ^3 container.7 with minecraft:air
item replace block ^-1 ^2 ^3 container.8 with minecraft:air
item replace block ^-1 ^2 ^3 container.9 with minecraft:air
item replace block ^-1 ^2 ^3 container.10 with minecraft:air
item replace block ^-1 ^2 ^3 container.11 with minecraft:air
item replace block ^-1 ^2 ^3 container.12 with minecraft:air
item replace block ^-1 ^2 ^3 container.13 with minecraft:air
item replace block ^-1 ^2 ^3 container.14 with minecraft:air
item replace block ^-1 ^2 ^3 container.15 with minecraft:air
item replace block ^-1 ^2 ^3 container.16 with minecraft:air
item replace block ^-1 ^2 ^3 container.17 with minecraft:air
item replace block ^-1 ^2 ^3 container.18 with minecraft:air
item replace block ^-1 ^2 ^3 container.19 with minecraft:air
item replace block ^-1 ^2 ^3 container.20 with minecraft:air
item replace block ^-1 ^2 ^3 container.21 with minecraft:air
item replace block ^-1 ^2 ^3 container.22 with minecraft:air
item replace block ^-1 ^2 ^3 container.23 with minecraft:air
item replace block ^-1 ^2 ^3 container.24 with minecraft:air
item replace block ^-1 ^2 ^3 container.25 with minecraft:air
item replace block ^-1 ^2 ^3 container.26 with minecraft:air
item replace block ^-1 ^2 ^4 container.0 with minecraft:air
item replace block ^-1 ^2 ^4 container.1 with minecraft:air
item replace block ^-1 ^2 ^4 container.2 with minecraft:air
item replace block ^-1 ^2 ^4 container.3 with minecraft:air
item replace block ^-1 ^2 ^4 container.4 with minecraft:air
item replace block ^-1 ^2 ^4 container.5 with minecraft:air
item replace block ^-1 ^2 ^4 container.6 with minecraft:air
item replace block ^-1 ^2 ^4 container.7 with minecraft:air
item replace block ^-1 ^2 ^4 container.8 with minecraft:air
item replace block ^-1 ^2 ^4 container.9 with minecraft:air
item replace block ^-1 ^2 ^4 container.10 with minecraft:air
item replace block ^-1 ^2 ^4 container.11 with minecraft:air
item replace block ^-1 ^2 ^4 container.12 with minecraft:air
item replace block ^-1 ^2 ^4 container.13 with minecraft:air
item replace block ^-1 ^2 ^4 container.14 with minecraft:air
item replace block ^-1 ^2 ^4 container.15 with minecraft:air
item replace block ^-1 ^2 ^4 container.16 with minecraft:air
item replace block ^-1 ^2 ^4 container.17 with minecraft:air
item replace block ^-1 ^2 ^4 container.18 with minecraft:air
item replace block ^-1 ^2 ^4 container.19 with minecraft:air
item replace block ^-1 ^2 ^4 container.20 with minecraft:air
item replace block ^-1 ^2 ^4 container.21 with minecraft:air
item replace block ^-1 ^2 ^4 container.22 with minecraft:air
item replace block ^-1 ^2 ^4 container.23 with minecraft:air
item replace block ^-1 ^2 ^4 container.24 with minecraft:air
item replace block ^-1 ^2 ^4 container.25 with minecraft:air
item replace block ^-1 ^2 ^4 container.26 with minecraft:air
item replace block ^-2 ^2 ^3 container.0 with minecraft:air
item replace block ^-2 ^2 ^3 container.1 with minecraft:air
item replace block ^-2 ^2 ^3 container.2 with minecraft:air
item replace block ^-2 ^2 ^3 container.3 with minecraft:air
item replace block ^-2 ^2 ^3 container.4 with minecraft:air
item replace block ^-2 ^2 ^3 container.5 with minecraft:air
item replace block ^-2 ^2 ^3 container.6 with minecraft:air
item replace block ^-2 ^2 ^3 container.7 with minecraft:air
item replace block ^-2 ^2 ^3 container.8 with minecraft:air
item replace block ^-2 ^2 ^3 container.9 with minecraft:air
item replace block ^-2 ^2 ^3 container.10 with minecraft:air
item replace block ^-2 ^2 ^3 container.11 with minecraft:air
item replace block ^-2 ^2 ^3 container.12 with minecraft:air
item replace block ^-2 ^2 ^3 container.13 with minecraft:air
item replace block ^-2 ^2 ^3 container.14 with minecraft:air
item replace block ^-2 ^2 ^3 container.15 with minecraft:air
item replace block ^-2 ^2 ^3 container.16 with minecraft:air
item replace block ^-2 ^2 ^3 container.17 with minecraft:air
item replace block ^-2 ^2 ^3 container.18 with minecraft:air
item replace block ^-2 ^2 ^3 container.19 with minecraft:air
item replace block ^-2 ^2 ^3 container.20 with minecraft:air
item replace block ^-2 ^2 ^3 container.21 with minecraft:air
item replace block ^-2 ^2 ^3 container.22 with minecraft:air
item replace block ^-2 ^2 ^3 container.23 with minecraft:air
item replace block ^-2 ^2 ^3 container.24 with minecraft:air
item replace block ^-2 ^2 ^3 container.25 with minecraft:air
item replace block ^-2 ^2 ^3 container.26 with minecraft:air
item replace block ^-2 ^2 ^4 container.0 with minecraft:air
item replace block ^-2 ^2 ^4 container.1 with minecraft:air
item replace block ^-2 ^2 ^4 container.2 with minecraft:air
item replace block ^-2 ^2 ^4 container.3 with minecraft:air
item replace block ^-2 ^2 ^4 container.4 with minecraft:air
item replace block ^-2 ^2 ^4 container.5 with minecraft:air
item replace block ^-2 ^2 ^4 container.6 with minecraft:air
item replace block ^-2 ^2 ^4 container.7 with minecraft:air
item replace block ^-2 ^2 ^4 container.8 with minecraft:air
item replace block ^-2 ^2 ^4 container.9 with minecraft:air
item replace block ^-2 ^2 ^4 container.10 with minecraft:air
item replace block ^-2 ^2 ^4 container.11 with minecraft:air
item replace block ^-2 ^2 ^4 container.12 with minecraft:air
item replace block ^-2 ^2 ^4 container.13 with minecraft:air
item replace block ^-2 ^2 ^4 container.14 with minecraft:air
item replace block ^-2 ^2 ^4 container.15 with minecraft:air
item replace block ^-2 ^2 ^4 container.16 with minecraft:air
item replace block ^-2 ^2 ^4 container.17 with minecraft:air
item replace block ^-2 ^2 ^4 container.18 with minecraft:air
item replace block ^-2 ^2 ^4 container.19 with minecraft:air
item replace block ^-2 ^2 ^4 container.20 with minecraft:air
item replace block ^-2 ^2 ^4 container.21 with minecraft:air
item replace block ^-2 ^2 ^4 container.22 with minecraft:air
item replace block ^-2 ^2 ^4 container.23 with minecraft:air
item replace block ^-2 ^2 ^4 container.24 with minecraft:air
item replace block ^-2 ^2 ^4 container.25 with minecraft:air
item replace block ^-2 ^2 ^4 container.26 with minecraft:air
item replace block ^-3 ^2 ^3 container.0 with minecraft:air
item replace block ^-3 ^2 ^3 container.1 with minecraft:air
item replace block ^-3 ^2 ^3 container.2 with minecraft:air
item replace block ^-3 ^2 ^3 container.3 with minecraft:air
item replace block ^-3 ^2 ^3 container.4 with minecraft:air
item replace block ^-3 ^2 ^3 container.5 with minecraft:air
item replace block ^-3 ^2 ^3 container.6 with minecraft:air
item replace block ^-3 ^2 ^3 container.7 with minecraft:air
item replace block ^-3 ^2 ^3 container.8 with minecraft:air
item replace block ^-3 ^2 ^3 container.9 with minecraft:air
item replace block ^-3 ^2 ^3 container.10 with minecraft:air
item replace block ^-3 ^2 ^3 container.11 with minecraft:air
item replace block ^-3 ^2 ^3 container.12 with minecraft:air
item replace block ^-3 ^2 ^3 container.13 with minecraft:air
item replace block ^-3 ^2 ^3 container.14 with minecraft:air
item replace block ^-3 ^2 ^3 container.15 with minecraft:air
item replace block ^-3 ^2 ^3 container.16 with minecraft:air
item replace block ^-3 ^2 ^3 container.17 with minecraft:air
item replace block ^-3 ^2 ^3 container.18 with minecraft:air
item replace block ^-3 ^2 ^3 container.19 with minecraft:air
item replace block ^-3 ^2 ^3 container.20 with minecraft:air
item replace block ^-3 ^2 ^3 container.21 with minecraft:air
item replace block ^-3 ^2 ^3 container.22 with minecraft:air
item replace block ^-3 ^2 ^3 container.23 with minecraft:air
item replace block ^-3 ^2 ^3 container.24 with minecraft:air
item replace block ^-3 ^2 ^3 container.25 with minecraft:air
item replace block ^-3 ^2 ^3 container.26 with minecraft:air
item replace block ^-3 ^2 ^4 container.0 with minecraft:air
item replace block ^-3 ^2 ^4 container.1 with minecraft:air
item replace block ^-3 ^2 ^4 container.2 with minecraft:air
item replace block ^-3 ^2 ^4 container.3 with minecraft:air
item replace block ^-3 ^2 ^4 container.4 with minecraft:air
item replace block ^-3 ^2 ^4 container.5 with minecraft:air
item replace block ^-3 ^2 ^4 container.6 with minecraft:air
item replace block ^-3 ^2 ^4 container.7 with minecraft:air
item replace block ^-3 ^2 ^4 container.8 with minecraft:air
item replace block ^-3 ^2 ^4 container.9 with minecraft:air
item replace block ^-3 ^2 ^4 container.10 with minecraft:air
item replace block ^-3 ^2 ^4 container.11 with minecraft:air
item replace block ^-3 ^2 ^4 container.12 with minecraft:air
item replace block ^-3 ^2 ^4 container.13 with minecraft:air
item replace block ^-3 ^2 ^4 container.14 with minecraft:air
item replace block ^-3 ^2 ^4 container.15 with minecraft:air
item replace block ^-3 ^2 ^4 container.16 with minecraft:air
item replace block ^-3 ^2 ^4 container.17 with minecraft:air
item replace block ^-3 ^2 ^4 container.18 with minecraft:air
item replace block ^-3 ^2 ^4 container.19 with minecraft:air
item replace block ^-3 ^2 ^4 container.20 with minecraft:air
item replace block ^-3 ^2 ^4 container.21 with minecraft:air
item replace block ^-3 ^2 ^4 container.22 with minecraft:air
item replace block ^-3 ^2 ^4 container.23 with minecraft:air
item replace block ^-3 ^2 ^4 container.24 with minecraft:air
item replace block ^-3 ^2 ^4 container.25 with minecraft:air
item replace block ^-3 ^2 ^4 container.26 with minecraft:air
item replace block ^-4 ^2 ^3 container.0 with minecraft:air
item replace block ^-4 ^2 ^3 container.1 with minecraft:air
item replace block ^-4 ^2 ^3 container.2 with minecraft:air
item replace block ^-4 ^2 ^3 container.3 with minecraft:air
item replace block ^-4 ^2 ^3 container.4 with minecraft:air
item replace block ^-4 ^2 ^3 container.5 with minecraft:air
item replace block ^-4 ^2 ^3 container.6 with minecraft:air
item replace block ^-4 ^2 ^3 container.7 with minecraft:air
item replace block ^-4 ^2 ^3 container.8 with minecraft:air
item replace block ^-4 ^2 ^3 container.9 with minecraft:air
item replace block ^-4 ^2 ^3 container.10 with minecraft:air
item replace block ^-4 ^2 ^3 container.11 with minecraft:air
item replace block ^-4 ^2 ^3 container.12 with minecraft:air
item replace block ^-4 ^2 ^3 container.13 with minecraft:air
item replace block ^-4 ^2 ^3 container.14 with minecraft:air
item replace block ^-4 ^2 ^3 container.15 with minecraft:air
item replace block ^-4 ^2 ^3 container.16 with minecraft:air
item replace block ^-4 ^2 ^3 container.17 with minecraft:air
item replace block ^-4 ^2 ^3 container.18 with minecraft:air
item replace block ^-4 ^2 ^3 container.19 with minecraft:air
item replace block ^-4 ^2 ^3 container.20 with minecraft:air
item replace block ^-4 ^2 ^3 container.21 with minecraft:air
item replace block ^-4 ^2 ^3 container.22 with minecraft:air
item replace block ^-4 ^2 ^3 container.23 with minecraft:air
item replace block ^-4 ^2 ^3 container.24 with minecraft:air
item replace block ^-4 ^2 ^3 container.25 with minecraft:air
item replace block ^-4 ^2 ^3 container.26 with minecraft:air
item replace block ^-4 ^2 ^4 container.0 with minecraft:air
item replace block ^-4 ^2 ^4 container.1 with minecraft:air
item replace block ^-4 ^2 ^4 container.2 with minecraft:air
item replace block ^-4 ^2 ^4 container.3 with minecraft:air
item replace block ^-4 ^2 ^4 container.4 with minecraft:air
item replace block ^-4 ^2 ^4 container.5 with minecraft:air
item replace block ^-4 ^2 ^4 container.6 with minecraft:air
item replace block ^-4 ^2 ^4 container.7 with minecraft:air
item replace block ^-4 ^2 ^4 container.8 with minecraft:air
item replace block ^-4 ^2 ^4 container.9 with minecraft:air
item replace block ^-4 ^2 ^4 container.10 with minecraft:air
item replace block ^-4 ^2 ^4 container.11 with minecraft:air
item replace block ^-4 ^2 ^4 container.12 with minecraft:air
item replace block ^-4 ^2 ^4 container.13 with minecraft:air
item replace block ^-4 ^2 ^4 container.14 with minecraft:air
item replace block ^-4 ^2 ^4 container.15 with minecraft:air
item replace block ^-4 ^2 ^4 container.16 with minecraft:air
item replace block ^-4 ^2 ^4 container.17 with minecraft:air
item replace block ^-4 ^2 ^4 container.18 with minecraft:air
item replace block ^-4 ^2 ^4 container.19 with minecraft:air
item replace block ^-4 ^2 ^4 container.20 with minecraft:air
item replace block ^-4 ^2 ^4 container.21 with minecraft:air
item replace block ^-4 ^2 ^4 container.22 with minecraft:air
item replace block ^-4 ^2 ^4 container.23 with minecraft:air
item replace block ^-4 ^2 ^4 container.24 with minecraft:air
item replace block ^-4 ^2 ^4 container.25 with minecraft:air
item replace block ^-4 ^2 ^4 container.26 with minecraft:air
item replace block ^-5 ^2 ^3 container.0 with minecraft:air
item replace block ^-5 ^2 ^3 container.1 with minecraft:air
item replace block ^-5 ^2 ^3 container.2 with minecraft:air
item replace block ^-5 ^2 ^3 container.3 with minecraft:air
item replace block ^-5 ^2 ^3 container.4 with minecraft:air
item replace block ^-5 ^2 ^3 container.5 with minecraft:air
item replace block ^-5 ^2 ^3 container.6 with minecraft:air
item replace block ^-5 ^2 ^3 container.7 with minecraft:air
item replace block ^-5 ^2 ^3 container.8 with minecraft:air
item replace block ^-5 ^2 ^3 container.9 with minecraft:air
item replace block ^-5 ^2 ^3 container.10 with minecraft:air
item replace block ^-5 ^2 ^3 container.11 with minecraft:air
item replace block ^-5 ^2 ^3 container.12 with minecraft:air
item replace block ^-5 ^2 ^3 container.13 with minecraft:air
item replace block ^-5 ^2 ^3 container.14 with minecraft:air
item replace block ^-5 ^2 ^3 container.15 with minecraft:air
item replace block ^-5 ^2 ^3 container.16 with minecraft:air
item replace block ^-5 ^2 ^3 container.17 with minecraft:air
item replace block ^-5 ^2 ^3 container.18 with minecraft:air
item replace block ^-5 ^2 ^3 container.19 with minecraft:air
item replace block ^-5 ^2 ^3 container.20 with minecraft:air
item replace block ^-5 ^2 ^3 container.21 with minecraft:air
item replace block ^-5 ^2 ^3 container.22 with minecraft:air
item replace block ^-5 ^2 ^3 container.23 with minecraft:air
item replace block ^-5 ^2 ^3 container.24 with minecraft:air
item replace block ^-5 ^2 ^3 container.25 with minecraft:air
item replace block ^-5 ^2 ^3 container.26 with minecraft:air
item replace block ^-5 ^2 ^4 container.0 with minecraft:air
item replace block ^-5 ^2 ^4 container.1 with minecraft:air
item replace block ^-5 ^2 ^4 container.2 with minecraft:air
item replace block ^-5 ^2 ^4 container.3 with minecraft:air
item replace block ^-5 ^2 ^4 container.4 with minecraft:air
item replace block ^-5 ^2 ^4 container.5 with minecraft:air
item replace block ^-5 ^2 ^4 container.6 with minecraft:air
item replace block ^-5 ^2 ^4 container.7 with minecraft:air
item replace block ^-5 ^2 ^4 container.8 with minecraft:air
item replace block ^-5 ^2 ^4 container.9 with minecraft:air
item replace block ^-5 ^2 ^4 container.10 with minecraft:air
item replace block ^-5 ^2 ^4 container.11 with minecraft:air
item replace block ^-5 ^2 ^4 container.12 with minecraft:air
item replace block ^-5 ^2 ^4 container.13 with minecraft:air
item replace block ^-5 ^2 ^4 container.14 with minecraft:air
item replace block ^-5 ^2 ^4 container.15 with minecraft:air
item replace block ^-5 ^2 ^4 container.16 with minecraft:air
item replace block ^-5 ^2 ^4 container.17 with minecraft:air
item replace block ^-5 ^2 ^4 container.18 with minecraft:air
item replace block ^-5 ^2 ^4 container.19 with minecraft:air
item replace block ^-5 ^2 ^4 container.20 with minecraft:air
item replace block ^-5 ^2 ^4 container.21 with minecraft:air
item replace block ^-5 ^2 ^4 container.22 with minecraft:air
item replace block ^-5 ^2 ^4 container.23 with minecraft:air
item replace block ^-5 ^2 ^4 container.24 with minecraft:air
item replace block ^-5 ^2 ^4 container.25 with minecraft:air
item replace block ^-5 ^2 ^4 container.26 with minecraft:air
item replace block ^-6 ^2 ^3 container.0 with minecraft:air
item replace block ^-6 ^2 ^3 container.1 with minecraft:air
item replace block ^-6 ^2 ^3 container.2 with minecraft:air
item replace block ^-6 ^2 ^3 container.3 with minecraft:air
item replace block ^-6 ^2 ^3 container.4 with minecraft:air
item replace block ^-6 ^2 ^3 container.5 with minecraft:air
item replace block ^-6 ^2 ^3 container.6 with minecraft:air
item replace block ^-6 ^2 ^3 container.7 with minecraft:air
item replace block ^-6 ^2 ^3 container.8 with minecraft:air
item replace block ^-6 ^2 ^3 container.9 with minecraft:air
item replace block ^-6 ^2 ^3 container.10 with minecraft:air
item replace block ^-6 ^2 ^3 container.11 with minecraft:air
item replace block ^-6 ^2 ^3 container.12 with minecraft:air
item replace block ^-6 ^2 ^3 container.13 with minecraft:air
item replace block ^-6 ^2 ^3 container.14 with minecraft:air
item replace block ^-6 ^2 ^3 container.15 with minecraft:air
item replace block ^-6 ^2 ^3 container.16 with minecraft:air
item replace block ^-6 ^2 ^3 container.17 with minecraft:air
item replace block ^-6 ^2 ^3 container.18 with minecraft:air
item replace block ^-6 ^2 ^3 container.19 with minecraft:air
item replace block ^-6 ^2 ^3 container.20 with minecraft:air
item replace block ^-6 ^2 ^3 container.21 with minecraft:air
item replace block ^-6 ^2 ^3 container.22 with minecraft:air
item replace block ^-6 ^2 ^3 container.23 with minecraft:air
item replace block ^-6 ^2 ^3 container.24 with minecraft:air
item replace block ^-6 ^2 ^3 container.25 with minecraft:air
item replace block ^-6 ^2 ^3 container.26 with minecraft:air
item replace block ^-6 ^2 ^4 container.0 with minecraft:air
item replace block ^-6 ^2 ^4 container.1 with minecraft:air
item replace block ^-6 ^2 ^4 container.2 with minecraft:air
item replace block ^-6 ^2 ^4 container.3 with minecraft:air
item replace block ^-6 ^2 ^4 container.4 with minecraft:air
item replace block ^-6 ^2 ^4 container.5 with minecraft:air
item replace block ^-6 ^2 ^4 container.6 with minecraft:air
item replace block ^-6 ^2 ^4 container.7 with minecraft:air
item replace block ^-6 ^2 ^4 container.8 with minecraft:air
item replace block ^-6 ^2 ^4 container.9 with minecraft:air
item replace block ^-6 ^2 ^4 container.10 with minecraft:air
item replace block ^-6 ^2 ^4 container.11 with minecraft:air
item replace block ^-6 ^2 ^4 container.12 with minecraft:air
item replace block ^-6 ^2 ^4 container.13 with minecraft:air
item replace block ^-6 ^2 ^4 container.14 with minecraft:air
item replace block ^-6 ^2 ^4 container.15 with minecraft:air
item replace block ^-6 ^2 ^4 container.16 with minecraft:air
item replace block ^-6 ^2 ^4 container.17 with minecraft:air
item replace block ^-6 ^2 ^4 container.18 with minecraft:air
item replace block ^-6 ^2 ^4 container.19 with minecraft:air
item replace block ^-6 ^2 ^4 container.20 with minecraft:air
item replace block ^-6 ^2 ^4 container.21 with minecraft:air
item replace block ^-6 ^2 ^4 container.22 with minecraft:air
item replace block ^-6 ^2 ^4 container.23 with minecraft:air
item replace block ^-6 ^2 ^4 container.24 with minecraft:air
item replace block ^-6 ^2 ^4 container.25 with minecraft:air
item replace block ^-6 ^2 ^4 container.26 with minecraft:air
item replace block ^-7 ^2 ^3 container.0 with minecraft:air
item replace block ^-7 ^2 ^3 container.1 with minecraft:air
item replace block ^-7 ^2 ^3 container.2 with minecraft:air
item replace block ^-7 ^2 ^3 container.3 with minecraft:air
item replace block ^-7 ^2 ^3 container.4 with minecraft:air
item replace block ^-7 ^2 ^3 container.5 with minecraft:air
item replace block ^-7 ^2 ^3 container.6 with minecraft:air
item replace block ^-7 ^2 ^3 container.7 with minecraft:air
item replace block ^-7 ^2 ^3 container.8 with minecraft:air
item replace block ^-7 ^2 ^3 container.9 with minecraft:air
item replace block ^-7 ^2 ^3 container.10 with minecraft:air
item replace block ^-7 ^2 ^3 container.11 with minecraft:air
item replace block ^-7 ^2 ^3 container.12 with minecraft:air
item replace block ^-7 ^2 ^3 container.13 with minecraft:air
item replace block ^-7 ^2 ^3 container.14 with minecraft:air
item replace block ^-7 ^2 ^3 container.15 with minecraft:air
item replace block ^-7 ^2 ^3 container.16 with minecraft:air
item replace block ^-7 ^2 ^3 container.17 with minecraft:air
item replace block ^-7 ^2 ^3 container.18 with minecraft:air
item replace block ^-7 ^2 ^3 container.19 with minecraft:air
item replace block ^-7 ^2 ^3 container.20 with minecraft:air
item replace block ^-7 ^2 ^3 container.21 with minecraft:air
item replace block ^-7 ^2 ^3 container.22 with minecraft:air
item replace block ^-7 ^2 ^3 container.23 with minecraft:air
item replace block ^-7 ^2 ^3 container.24 with minecraft:air
item replace block ^-7 ^2 ^3 container.25 with minecraft:air
item replace block ^-7 ^2 ^3 container.26 with minecraft:air
item replace block ^-7 ^2 ^4 container.0 with minecraft:air
item replace block ^-7 ^2 ^4 container.1 with minecraft:air
item replace block ^-7 ^2 ^4 container.2 with minecraft:air
item replace block ^-7 ^2 ^4 container.3 with minecraft:air
item replace block ^-7 ^2 ^4 container.4 with minecraft:air
item replace block ^-7 ^2 ^4 container.5 with minecraft:air
item replace block ^-7 ^2 ^4 container.6 with minecraft:air
item replace block ^-7 ^2 ^4 container.7 with minecraft:air
item replace block ^-7 ^2 ^4 container.8 with minecraft:air
item replace block ^-7 ^2 ^4 container.9 with minecraft:air
item replace block ^-7 ^2 ^4 container.10 with minecraft:air
item replace block ^-7 ^2 ^4 container.11 with minecraft:air
item replace block ^-7 ^2 ^4 container.12 with minecraft:air
item replace block ^-7 ^2 ^4 container.13 with minecraft:air
item replace block ^-7 ^2 ^4 container.14 with minecraft:air
item replace block ^-7 ^2 ^4 container.15 with minecraft:air
item replace block ^-7 ^2 ^4 container.16 with minecraft:air
item replace block ^-7 ^2 ^4 container.17 with minecraft:air
item replace block ^-7 ^2 ^4 container.18 with minecraft:air
item replace block ^-7 ^2 ^4 container.19 with minecraft:air
item replace block ^-7 ^2 ^4 container.20 with minecraft:air
item replace block ^-7 ^2 ^4 container.21 with minecraft:air
item replace block ^-7 ^2 ^4 container.22 with minecraft:air
item replace block ^-7 ^2 ^4 container.23 with minecraft:air
item replace block ^-7 ^2 ^4 container.24 with minecraft:air
item replace block ^-7 ^2 ^4 container.25 with minecraft:air
item replace block ^-7 ^2 ^4 container.26 with minecraft:air
item replace block ^-8 ^2 ^3 container.0 with minecraft:air
item replace block ^-8 ^2 ^3 container.1 with minecraft:air
item replace block ^-8 ^2 ^3 container.2 with minecraft:air
item replace block ^-8 ^2 ^3 container.3 with minecraft:air
item replace block ^-8 ^2 ^3 container.4 with minecraft:air
item replace block ^-8 ^2 ^3 container.5 with minecraft:air
item replace block ^-8 ^2 ^3 container.6 with minecraft:air
item replace block ^-8 ^2 ^3 container.7 with minecraft:air
item replace block ^-8 ^2 ^3 container.8 with minecraft:air
item replace block ^-8 ^2 ^3 container.9 with minecraft:air
item replace block ^-8 ^2 ^3 container.10 with minecraft:air
item replace block ^-8 ^2 ^3 container.11 with minecraft:air
item replace block ^-8 ^2 ^3 container.12 with minecraft:air
item replace block ^-8 ^2 ^3 container.13 with minecraft:air
item replace block ^-8 ^2 ^3 container.14 with minecraft:air
item replace block ^-8 ^2 ^3 container.15 with minecraft:air
item replace block ^-8 ^2 ^3 container.16 with minecraft:air
item replace block ^-8 ^2 ^3 container.17 with minecraft:air
item replace block ^-8 ^2 ^3 container.18 with minecraft:air
item replace block ^-8 ^2 ^3 container.19 with minecraft:air
item replace block ^-8 ^2 ^3 container.20 with minecraft:air
item replace block ^-8 ^2 ^3 container.21 with minecraft:air
item replace block ^-8 ^2 ^3 container.22 with minecraft:air
item replace block ^-8 ^2 ^3 container.23 with minecraft:air
item replace block ^-8 ^2 ^3 container.24 with minecraft:air
item replace block ^-8 ^2 ^3 container.25 with minecraft:air
item replace block ^-8 ^2 ^3 container.26 with minecraft:air
item replace block ^-8 ^2 ^4 container.0 with minecraft:air
item replace block ^-8 ^2 ^4 container.1 with minecraft:air
item replace block ^-8 ^2 ^4 container.2 with minecraft:air
item replace block ^-8 ^2 ^4 container.3 with minecraft:air
item replace block ^-8 ^2 ^4 container.4 with minecraft:air
item replace block ^-8 ^2 ^4 container.5 with minecraft:air
item replace block ^-8 ^2 ^4 container.6 with minecraft:air
item replace block ^-8 ^2 ^4 container.7 with minecraft:air
item replace block ^-8 ^2 ^4 container.8 with minecraft:air
item replace block ^-8 ^2 ^4 container.9 with minecraft:air
item replace block ^-8 ^2 ^4 container.10 with minecraft:air
item replace block ^-8 ^2 ^4 container.11 with minecraft:air
item replace block ^-8 ^2 ^4 container.12 with minecraft:air
item replace block ^-8 ^2 ^4 container.13 with minecraft:air
item replace block ^-8 ^2 ^4 container.14 with minecraft:air
item replace block ^-8 ^2 ^4 container.15 with minecraft:air
item replace block ^-8 ^2 ^4 container.16 with minecraft:air
item replace block ^-8 ^2 ^4 container.17 with minecraft:air
item replace block ^-8 ^2 ^4 container.18 with minecraft:air
item replace block ^-8 ^2 ^4 container.19 with minecraft:air
item replace block ^-8 ^2 ^4 container.20 with minecraft:air
item replace block ^-8 ^2 ^4 container.21 with minecraft:air
item replace block ^-8 ^2 ^4 container.22 with minecraft:air
item replace block ^-8 ^2 ^4 container.23 with minecraft:air
item replace block ^-8 ^2 ^4 container.24 with minecraft:air
item replace block ^-8 ^2 ^4 container.25 with minecraft:air
item replace block ^-8 ^2 ^4 container.26 with minecraft:air
item replace block ^-9 ^2 ^3 container.0 with minecraft:air
item replace block ^-9 ^2 ^3 container.1 with minecraft:air
item replace block ^-9 ^2 ^3 container.2 with minecraft:air
item replace block ^-9 ^2 ^3 container.3 with minecraft:air
item replace block ^-9 ^2 ^3 container.4 with minecraft:air
item replace block ^-9 ^2 ^3 container.5 with minecraft:air
item replace block ^-9 ^2 ^3 container.6 with minecraft:air
item replace block ^-9 ^2 ^3 container.7 with minecraft:air
item replace block ^-9 ^2 ^3 container.8 with minecraft:air
item replace block ^-9 ^2 ^3 container.9 with minecraft:air
item replace block ^-9 ^2 ^3 container.10 with minecraft:air
item replace block ^-9 ^2 ^3 container.11 with minecraft:air
item replace block ^-9 ^2 ^3 container.12 with minecraft:air
item replace block ^-9 ^2 ^3 container.13 with minecraft:air
item replace block ^-9 ^2 ^3 container.14 with minecraft:air
item replace block ^-9 ^2 ^3 container.15 with minecraft:air
item replace block ^-9 ^2 ^3 container.16 with minecraft:air
item replace block ^-9 ^2 ^3 container.17 with minecraft:air
item replace block ^-9 ^2 ^3 container.18 with minecraft:air
item replace block ^-9 ^2 ^3 container.19 with minecraft:air
item replace block ^-9 ^2 ^3 container.20 with minecraft:air
item replace block ^-9 ^2 ^3 container.21 with minecraft:air
item replace block ^-9 ^2 ^3 container.22 with minecraft:air
item replace block ^-9 ^2 ^3 container.23 with minecraft:air
item replace block ^-9 ^2 ^3 container.24 with minecraft:air
item replace block ^-9 ^2 ^3 container.25 with minecraft:air
item replace block ^-9 ^2 ^3 container.26 with minecraft:air
item replace block ^-9 ^2 ^4 container.0 with minecraft:air
item replace block ^-9 ^2 ^4 container.1 with minecraft:air
item replace block ^-9 ^2 ^4 container.2 with minecraft:air
item replace block ^-9 ^2 ^4 container.3 with minecraft:air
item replace block ^-9 ^2 ^4 container.4 with minecraft:air
item replace block ^-9 ^2 ^4 container.5 with minecraft:air
item replace block ^-9 ^2 ^4 container.6 with minecraft:air
item replace block ^-9 ^2 ^4 container.7 with minecraft:air
item replace block ^-9 ^2 ^4 container.8 with minecraft:air
item replace block ^-9 ^2 ^4 container.9 with minecraft:air
item replace block ^-9 ^2 ^4 container.10 with minecraft:air
item replace block ^-9 ^2 ^4 container.11 with minecraft:air
item replace block ^-9 ^2 ^4 container.12 with minecraft:air
item replace block ^-9 ^2 ^4 container.13 with minecraft:air
item replace block ^-9 ^2 ^4 container.14 with minecraft:air
item replace block ^-9 ^2 ^4 container.15 with minecraft:air
item replace block ^-9 ^2 ^4 container.16 with minecraft:air
item replace block ^-9 ^2 ^4 container.17 with minecraft:air
item replace block ^-9 ^2 ^4 container.18 with minecraft:air
item replace block ^-9 ^2 ^4 container.19 with minecraft:air
item replace block ^-9 ^2 ^4 container.20 with minecraft:air
item replace block ^-9 ^2 ^4 container.21 with minecraft:air
item replace block ^-9 ^2 ^4 container.22 with minecraft:air
item replace block ^-9 ^2 ^4 container.23 with minecraft:air
item replace block ^-9 ^2 ^4 container.24 with minecraft:air
item replace block ^-9 ^2 ^4 container.25 with minecraft:air
item replace block ^-9 ^2 ^4 container.26 with minecraft:air
item replace block ^-10 ^2 ^3 container.0 with minecraft:air
item replace block ^-10 ^2 ^3 container.1 with minecraft:air
item replace block ^-10 ^2 ^3 container.2 with minecraft:air
item replace block ^-10 ^2 ^3 container.3 with minecraft:air
item replace block ^-10 ^2 ^3 container.4 with minecraft:air
item replace block ^-10 ^2 ^3 container.5 with minecraft:air
item replace block ^-10 ^2 ^3 container.6 with minecraft:air
item replace block ^-10 ^2 ^3 container.7 with minecraft:air
item replace block ^-10 ^2 ^3 container.8 with minecraft:air
item replace block ^-10 ^2 ^3 container.9 with minecraft:air
item replace block ^-10 ^2 ^3 container.10 with minecraft:air
item replace block ^-10 ^2 ^3 container.11 with minecraft:air
item replace block ^-10 ^2 ^3 container.12 with minecraft:air
item replace block ^-10 ^2 ^3 container.13 with minecraft:air
item replace block ^-10 ^2 ^3 container.14 with minecraft:air
item replace block ^-10 ^2 ^3 container.15 with minecraft:air
item replace block ^-10 ^2 ^3 container.16 with minecraft:air
item replace block ^-10 ^2 ^3 container.17 with minecraft:air
item replace block ^-10 ^2 ^3 container.18 with minecraft:air
item replace block ^-10 ^2 ^3 container.19 with minecraft:air
item replace block ^-10 ^2 ^3 container.20 with minecraft:air
item replace block ^-10 ^2 ^3 container.21 with minecraft:air
item replace block ^-10 ^2 ^3 container.22 with minecraft:air
item replace block ^-10 ^2 ^3 container.23 with minecraft:air
item replace block ^-10 ^2 ^3 container.24 with minecraft:air
item replace block ^-10 ^2 ^3 container.25 with minecraft:air
item replace block ^-10 ^2 ^3 container.26 with minecraft:air
item replace block ^-10 ^2 ^4 container.0 with minecraft:air
item replace block ^-10 ^2 ^4 container.1 with minecraft:air
item replace block ^-10 ^2 ^4 container.2 with minecraft:air
item replace block ^-10 ^2 ^4 container.3 with minecraft:air
item replace block ^-10 ^2 ^4 container.4 with minecraft:air
item replace block ^-10 ^2 ^4 container.5 with minecraft:air
item replace block ^-10 ^2 ^4 container.6 with minecraft:air
item replace block ^-10 ^2 ^4 container.7 with minecraft:air
item replace block ^-10 ^2 ^4 container.8 with minecraft:air
item replace block ^-10 ^2 ^4 container.9 with minecraft:air
item replace block ^-10 ^2 ^4 container.10 with minecraft:air
item replace block ^-10 ^2 ^4 container.11 with minecraft:air
item replace block ^-10 ^2 ^4 container.12 with minecraft:air
item replace block ^-10 ^2 ^4 container.13 with minecraft:air
item replace block ^-10 ^2 ^4 container.14 with minecraft:air
item replace block ^-10 ^2 ^4 container.15 with minecraft:air
item replace block ^-10 ^2 ^4 container.16 with minecraft:air
item replace block ^-10 ^2 ^4 container.17 with minecraft:air
item replace block ^-10 ^2 ^4 container.18 with minecraft:air
item replace block ^-10 ^2 ^4 container.19 with minecraft:air
item replace block ^-10 ^2 ^4 container.20 with minecraft:air
item replace block ^-10 ^2 ^4 container.21 with minecraft:air
item replace block ^-10 ^2 ^4 container.22 with minecraft:air
item replace block ^-10 ^2 ^4 container.23 with minecraft:air
item replace block ^-10 ^2 ^4 container.24 with minecraft:air
item replace block ^-10 ^2 ^4 container.25 with minecraft:air
item replace block ^-10 ^2 ^4 container.26 with minecraft:air
item replace block ^-11 ^2 ^3 container.0 with minecraft:air
item replace block ^-11 ^2 ^3 container.1 with minecraft:air
item replace block ^-11 ^2 ^3 container.2 with minecraft:air
item replace block ^-11 ^2 ^3 container.3 with minecraft:air
item replace block ^-11 ^2 ^3 container.4 with minecraft:air
item replace block ^-11 ^2 ^3 container.5 with minecraft:air
item replace block ^-11 ^2 ^3 container.6 with minecraft:air
item replace block ^-11 ^2 ^3 container.7 with minecraft:air
item replace block ^-11 ^2 ^3 container.8 with minecraft:air
item replace block ^-11 ^2 ^3 container.9 with minecraft:air
item replace block ^-11 ^2 ^3 container.10 with minecraft:air
item replace block ^-11 ^2 ^3 container.11 with minecraft:air
item replace block ^-11 ^2 ^3 container.12 with minecraft:air
item replace block ^-11 ^2 ^3 container.13 with minecraft:air
item replace block ^-11 ^2 ^3 container.14 with minecraft:air
item replace block ^-11 ^2 ^3 container.15 with minecraft:air
item replace block ^-11 ^2 ^3 container.16 with minecraft:air
item replace block ^-11 ^2 ^3 container.17 with minecraft:air
item replace block ^-11 ^2 ^3 container.18 with minecraft:air
item replace block ^-11 ^2 ^3 container.19 with minecraft:air
item replace block ^-11 ^2 ^3 container.20 with minecraft:air
item replace block ^-11 ^2 ^3 container.21 with minecraft:air
item replace block ^-11 ^2 ^3 container.22 with minecraft:air
item replace block ^-11 ^2 ^3 container.23 with minecraft:air
item replace block ^-11 ^2 ^3 container.24 with minecraft:air
item replace block ^-11 ^2 ^3 container.25 with minecraft:air
item replace block ^-11 ^2 ^3 container.26 with minecraft:air
item replace block ^-11 ^2 ^4 container.0 with minecraft:air
item replace block ^-11 ^2 ^4 container.1 with minecraft:air
item replace block ^-11 ^2 ^4 container.2 with minecraft:air
item replace block ^-11 ^2 ^4 container.3 with minecraft:air
item replace block ^-11 ^2 ^4 container.4 with minecraft:air
item replace block ^-11 ^2 ^4 container.5 with minecraft:air
item replace block ^-11 ^2 ^4 container.6 with minecraft:air
item replace block ^-11 ^2 ^4 container.7 with minecraft:air
item replace block ^-11 ^2 ^4 container.8 with minecraft:air
item replace block ^-11 ^2 ^4 container.9 with minecraft:air
item replace block ^-11 ^2 ^4 container.10 with minecraft:air
item replace block ^-11 ^2 ^4 container.11 with minecraft:air
item replace block ^-11 ^2 ^4 container.12 with minecraft:air
item replace block ^-11 ^2 ^4 container.13 with minecraft:air
item replace block ^-11 ^2 ^4 container.14 with minecraft:air
item replace block ^-11 ^2 ^4 container.15 with minecraft:air
item replace block ^-11 ^2 ^4 container.16 with minecraft:air
item replace block ^-11 ^2 ^4 container.17 with minecraft:air
item replace block ^-11 ^2 ^4 container.18 with minecraft:air
item replace block ^-11 ^2 ^4 container.19 with minecraft:air
item replace block ^-11 ^2 ^4 container.20 with minecraft:air
item replace block ^-11 ^2 ^4 container.21 with minecraft:air
item replace block ^-11 ^2 ^4 container.22 with minecraft:air
item replace block ^-11 ^2 ^4 container.23 with minecraft:air
item replace block ^-11 ^2 ^4 container.24 with minecraft:air
item replace block ^-11 ^2 ^4 container.25 with minecraft:air
item replace block ^-11 ^2 ^4 container.26 with minecraft:air
item replace block ^-12 ^2 ^3 container.0 with minecraft:air
item replace block ^-12 ^2 ^3 container.1 with minecraft:air
item replace block ^-12 ^2 ^3 container.2 with minecraft:air
item replace block ^-12 ^2 ^3 container.3 with minecraft:air
item replace block ^-12 ^2 ^3 container.4 with minecraft:air
item replace block ^-12 ^2 ^3 container.5 with minecraft:air
item replace block ^-12 ^2 ^3 container.6 with minecraft:air
item replace block ^-12 ^2 ^3 container.7 with minecraft:air
item replace block ^-12 ^2 ^3 container.8 with minecraft:air
item replace block ^-12 ^2 ^3 container.9 with minecraft:air
item replace block ^-12 ^2 ^3 container.10 with minecraft:air
item replace block ^-12 ^2 ^3 container.11 with minecraft:air
item replace block ^-12 ^2 ^3 container.12 with minecraft:air
item replace block ^-12 ^2 ^3 container.13 with minecraft:air
item replace block ^-12 ^2 ^3 container.14 with minecraft:air
item replace block ^-12 ^2 ^3 container.15 with minecraft:air
item replace block ^-12 ^2 ^3 container.16 with minecraft:air
item replace block ^-12 ^2 ^3 container.17 with minecraft:air
item replace block ^-12 ^2 ^3 container.18 with minecraft:air
item replace block ^-12 ^2 ^3 container.19 with minecraft:air
item replace block ^-12 ^2 ^3 container.20 with minecraft:air
item replace block ^-12 ^2 ^3 container.21 with minecraft:air
item replace block ^-12 ^2 ^3 container.22 with minecraft:air
item replace block ^-12 ^2 ^3 container.23 with minecraft:air
item replace block ^-12 ^2 ^3 container.24 with minecraft:air
item replace block ^-12 ^2 ^3 container.25 with minecraft:air
item replace block ^-12 ^2 ^3 container.26 with minecraft:air
item replace block ^-12 ^2 ^4 container.0 with minecraft:air
item replace block ^-12 ^2 ^4 container.1 with minecraft:air
item replace block ^-12 ^2 ^4 container.2 with minecraft:air
item replace block ^-12 ^2 ^4 container.3 with minecraft:air
item replace block ^-12 ^2 ^4 container.4 with minecraft:air
item replace block ^-12 ^2 ^4 container.5 with minecraft:air
item replace block ^-12 ^2 ^4 container.6 with minecraft:air
item replace block ^-12 ^2 ^4 container.7 with minecraft:air
item replace block ^-12 ^2 ^4 container.8 with minecraft:air
item replace block ^-12 ^2 ^4 container.9 with minecraft:air
item replace block ^-12 ^2 ^4 container.10 with minecraft:air
item replace block ^-12 ^2 ^4 container.11 with minecraft:air
item replace block ^-12 ^2 ^4 container.12 with minecraft:air
item replace block ^-12 ^2 ^4 container.13 with minecraft:air
item replace block ^-12 ^2 ^4 container.14 with minecraft:air
item replace block ^-12 ^2 ^4 container.15 with minecraft:air
item replace block ^-12 ^2 ^4 container.16 with minecraft:air
item replace block ^-12 ^2 ^4 container.17 with minecraft:air
item replace block ^-12 ^2 ^4 container.18 with minecraft:air
item replace block ^-12 ^2 ^4 container.19 with minecraft:air
item replace block ^-12 ^2 ^4 container.20 with minecraft:air
item replace block ^-12 ^2 ^4 container.21 with minecraft:air
item replace block ^-12 ^2 ^4 container.22 with minecraft:air
item replace block ^-12 ^2 ^4 container.23 with minecraft:air
item replace block ^-12 ^2 ^4 container.24 with minecraft:air
item replace block ^-12 ^2 ^4 container.25 with minecraft:air
item replace block ^-12 ^2 ^4 container.26 with minecraft:air
item replace block ^-13 ^2 ^3 container.0 with minecraft:air
item replace block ^-13 ^2 ^3 container.1 with minecraft:air
item replace block ^-13 ^2 ^3 container.2 with minecraft:air
item replace block ^-13 ^2 ^3 container.3 with minecraft:air
item replace block ^-13 ^2 ^3 container.4 with minecraft:air
item replace block ^-13 ^2 ^3 container.5 with minecraft:air
item replace block ^-13 ^2 ^3 container.6 with minecraft:air
item replace block ^-13 ^2 ^3 container.7 with minecraft:air
item replace block ^-13 ^2 ^3 container.8 with minecraft:air
item replace block ^-13 ^2 ^3 container.9 with minecraft:air
item replace block ^-13 ^2 ^3 container.10 with minecraft:air
item replace block ^-13 ^2 ^3 container.11 with minecraft:air
item replace block ^-13 ^2 ^3 container.12 with minecraft:air
item replace block ^-13 ^2 ^3 container.13 with minecraft:air
item replace block ^-13 ^2 ^3 container.14 with minecraft:air
item replace block ^-13 ^2 ^3 container.15 with minecraft:air
item replace block ^-13 ^2 ^3 container.16 with minecraft:air
item replace block ^-13 ^2 ^3 container.17 with minecraft:air
item replace block ^-13 ^2 ^3 container.18 with minecraft:air
item replace block ^-13 ^2 ^3 container.19 with minecraft:air
item replace block ^-13 ^2 ^3 container.20 with minecraft:air
item replace block ^-13 ^2 ^3 container.21 with minecraft:air
item replace block ^-13 ^2 ^3 container.22 with minecraft:air
item replace block ^-13 ^2 ^3 container.23 with minecraft:air
item replace block ^-13 ^2 ^3 container.24 with minecraft:air
item replace block ^-13 ^2 ^3 container.25 with minecraft:air
item replace block ^-13 ^2 ^3 container.26 with minecraft:air
item replace block ^-13 ^2 ^4 container.0 with minecraft:air
item replace block ^-13 ^2 ^4 container.1 with minecraft:air
item replace block ^-13 ^2 ^4 container.2 with minecraft:air
item replace block ^-13 ^2 ^4 container.3 with minecraft:air
item replace block ^-13 ^2 ^4 container.4 with minecraft:air
item replace block ^-13 ^2 ^4 container.5 with minecraft:air
item replace block ^-13 ^2 ^4 container.6 with minecraft:air
item replace block ^-13 ^2 ^4 container.7 with minecraft:air
item replace block ^-13 ^2 ^4 container.8 with minecraft:air
item replace block ^-13 ^2 ^4 container.9 with minecraft:air
item replace block ^-13 ^2 ^4 container.10 with minecraft:air
item replace block ^-13 ^2 ^4 container.11 with minecraft:air
item replace block ^-13 ^2 ^4 container.12 with minecraft:air
item replace block ^-13 ^2 ^4 container.13 with minecraft:air
item replace block ^-13 ^2 ^4 container.14 with minecraft:air
item replace block ^-13 ^2 ^4 container.15 with minecraft:air
item replace block ^-13 ^2 ^4 container.16 with minecraft:air
item replace block ^-13 ^2 ^4 container.17 with minecraft:air
item replace block ^-13 ^2 ^4 container.18 with minecraft:air
item replace block ^-13 ^2 ^4 container.19 with minecraft:air
item replace block ^-13 ^2 ^4 container.20 with minecraft:air
item replace block ^-13 ^2 ^4 container.21 with minecraft:air
item replace block ^-13 ^2 ^4 container.22 with minecraft:air
item replace block ^-13 ^2 ^4 container.23 with minecraft:air
item replace block ^-13 ^2 ^4 container.24 with minecraft:air
item replace block ^-13 ^2 ^4 container.25 with minecraft:air
item replace block ^-13 ^2 ^4 container.26 with minecraft:air
item replace block ^-14 ^2 ^3 container.0 with minecraft:air
item replace block ^-14 ^2 ^3 container.1 with minecraft:air
item replace block ^-14 ^2 ^3 container.2 with minecraft:air
item replace block ^-14 ^2 ^3 container.3 with minecraft:air
item replace block ^-14 ^2 ^3 container.4 with minecraft:air
item replace block ^-14 ^2 ^3 container.5 with minecraft:air
item replace block ^-14 ^2 ^3 container.6 with minecraft:air
item replace block ^-14 ^2 ^3 container.7 with minecraft:air
item replace block ^-14 ^2 ^3 container.8 with minecraft:air
item replace block ^-14 ^2 ^3 container.9 with minecraft:air
item replace block ^-14 ^2 ^3 container.10 with minecraft:air
item replace block ^-14 ^2 ^3 container.11 with minecraft:air
item replace block ^-14 ^2 ^3 container.12 with minecraft:air
item replace block ^-14 ^2 ^3 container.13 with minecraft:air
item replace block ^-14 ^2 ^3 container.14 with minecraft:air
item replace block ^-14 ^2 ^3 container.15 with minecraft:air
item replace block ^-14 ^2 ^3 container.16 with minecraft:air
item replace block ^-14 ^2 ^3 container.17 with minecraft:air
item replace block ^-14 ^2 ^3 container.18 with minecraft:air
item replace block ^-14 ^2 ^3 container.19 with minecraft:air
item replace block ^-14 ^2 ^3 container.20 with minecraft:air
item replace block ^-14 ^2 ^3 container.21 with minecraft:air
item replace block ^-14 ^2 ^3 container.22 with minecraft:air
item replace block ^-14 ^2 ^3 container.23 with minecraft:air
item replace block ^-14 ^2 ^3 container.24 with minecraft:air
item replace block ^-14 ^2 ^3 container.25 with minecraft:air
item replace block ^-14 ^2 ^3 container.26 with minecraft:air
item replace block ^-14 ^2 ^4 container.0 with minecraft:air
item replace block ^-14 ^2 ^4 container.1 with minecraft:air
item replace block ^-14 ^2 ^4 container.2 with minecraft:air
item replace block ^-14 ^2 ^4 container.3 with minecraft:air
item replace block ^-14 ^2 ^4 container.4 with minecraft:air
item replace block ^-14 ^2 ^4 container.5 with minecraft:air
item replace block ^-14 ^2 ^4 container.6 with minecraft:air
item replace block ^-14 ^2 ^4 container.7 with minecraft:air
item replace block ^-14 ^2 ^4 container.8 with minecraft:air
item replace block ^-14 ^2 ^4 container.9 with minecraft:air
item replace block ^-14 ^2 ^4 container.10 with minecraft:air
item replace block ^-14 ^2 ^4 container.11 with minecraft:air
item replace block ^-14 ^2 ^4 container.12 with minecraft:air
item replace block ^-14 ^2 ^4 container.13 with minecraft:air
item replace block ^-14 ^2 ^4 container.14 with minecraft:air
item replace block ^-14 ^2 ^4 container.15 with minecraft:air
item replace block ^-14 ^2 ^4 container.16 with minecraft:air
item replace block ^-14 ^2 ^4 container.17 with minecraft:air
item replace block ^-14 ^2 ^4 container.18 with minecraft:air
item replace block ^-14 ^2 ^4 container.19 with minecraft:air
item replace block ^-14 ^2 ^4 container.20 with minecraft:air
item replace block ^-14 ^2 ^4 container.21 with minecraft:air
item replace block ^-14 ^2 ^4 container.22 with minecraft:air
item replace block ^-14 ^2 ^4 container.23 with minecraft:air
item replace block ^-14 ^2 ^4 container.24 with minecraft:air
item replace block ^-14 ^2 ^4 container.25 with minecraft:air
item replace block ^-14 ^2 ^4 container.26 with minecraft:air
item replace block ^-15 ^2 ^3 container.0 with minecraft:air
item replace block ^-15 ^2 ^3 container.1 with minecraft:air
item replace block ^-15 ^2 ^3 container.2 with minecraft:air
item replace block ^-15 ^2 ^3 container.3 with minecraft:air
item replace block ^-15 ^2 ^3 container.4 with minecraft:air
item replace block ^-15 ^2 ^3 container.5 with minecraft:air
item replace block ^-15 ^2 ^3 container.6 with minecraft:air
item replace block ^-15 ^2 ^3 container.7 with minecraft:air
item replace block ^-15 ^2 ^3 container.8 with minecraft:air
item replace block ^-15 ^2 ^3 container.9 with minecraft:air
item replace block ^-15 ^2 ^3 container.10 with minecraft:air
item replace block ^-15 ^2 ^3 container.11 with minecraft:air
item replace block ^-15 ^2 ^3 container.12 with minecraft:air
item replace block ^-15 ^2 ^3 container.13 with minecraft:air
item replace block ^-15 ^2 ^3 container.14 with minecraft:air
item replace block ^-15 ^2 ^3 container.15 with minecraft:air
item replace block ^-15 ^2 ^3 container.16 with minecraft:air
item replace block ^-15 ^2 ^3 container.17 with minecraft:air
item replace block ^-15 ^2 ^3 container.18 with minecraft:air
item replace block ^-15 ^2 ^3 container.19 with minecraft:air
item replace block ^-15 ^2 ^3 container.20 with minecraft:air
item replace block ^-15 ^2 ^3 container.21 with minecraft:air
item replace block ^-15 ^2 ^3 container.22 with minecraft:air
item replace block ^-15 ^2 ^3 container.23 with minecraft:air
item replace block ^-15 ^2 ^3 container.24 with minecraft:air
item replace block ^-15 ^2 ^3 container.25 with minecraft:air
item replace block ^-15 ^2 ^3 container.26 with minecraft:air
item replace block ^-15 ^2 ^4 container.0 with minecraft:air
item replace block ^-15 ^2 ^4 container.1 with minecraft:air
item replace block ^-15 ^2 ^4 container.2 with minecraft:air
item replace block ^-15 ^2 ^4 container.3 with minecraft:air
item replace block ^-15 ^2 ^4 container.4 with minecraft:air
item replace block ^-15 ^2 ^4 container.5 with minecraft:air
item replace block ^-15 ^2 ^4 container.6 with minecraft:air
item replace block ^-15 ^2 ^4 container.7 with minecraft:air
item replace block ^-15 ^2 ^4 container.8 with minecraft:air
item replace block ^-15 ^2 ^4 container.9 with minecraft:air
item replace block ^-15 ^2 ^4 container.10 with minecraft:air
item replace block ^-15 ^2 ^4 container.11 with minecraft:air
item replace block ^-15 ^2 ^4 container.12 with minecraft:air
item replace block ^-15 ^2 ^4 container.13 with minecraft:air
item replace block ^-15 ^2 ^4 container.14 with minecraft:air
item replace block ^-15 ^2 ^4 container.15 with minecraft:air
item replace block ^-15 ^2 ^4 container.16 with minecraft:air
item replace block ^-15 ^2 ^4 container.17 with minecraft:air
item replace block ^-15 ^2 ^4 container.18 with minecraft:air
item replace block ^-15 ^2 ^4 container.19 with minecraft:air
item replace block ^-15 ^2 ^4 container.20 with minecraft:air
item replace block ^-15 ^2 ^4 container.21 with minecraft:air
item replace block ^-15 ^2 ^4 container.22 with minecraft:air
item replace block ^-15 ^2 ^4 container.23 with minecraft:air
item replace block ^-15 ^2 ^4 container.24 with minecraft:air
item replace block ^-15 ^2 ^4 container.25 with minecraft:air
item replace block ^-15 ^2 ^4 container.26 with minecraft:air
item replace block ^-16 ^2 ^3 container.0 with minecraft:air
item replace block ^-16 ^2 ^3 container.1 with minecraft:air
item replace block ^-16 ^2 ^3 container.2 with minecraft:air
item replace block ^-16 ^2 ^3 container.3 with minecraft:air
item replace block ^-16 ^2 ^3 container.4 with minecraft:air
item replace block ^-16 ^2 ^3 container.5 with minecraft:air
item replace block ^-16 ^2 ^3 container.6 with minecraft:air
item replace block ^-16 ^2 ^3 container.7 with minecraft:air
item replace block ^-16 ^2 ^3 container.8 with minecraft:air
item replace block ^-16 ^2 ^3 container.9 with minecraft:air
item replace block ^-16 ^2 ^3 container.10 with minecraft:air
item replace block ^-16 ^2 ^3 container.11 with minecraft:air
item replace block ^-16 ^2 ^3 container.12 with minecraft:air
item replace block ^-16 ^2 ^3 container.13 with minecraft:air
item replace block ^-16 ^2 ^3 container.14 with minecraft:air
item replace block ^-16 ^2 ^3 container.15 with minecraft:air
item replace block ^-16 ^2 ^3 container.16 with minecraft:air
item replace block ^-16 ^2 ^3 container.17 with minecraft:air
item replace block ^-16 ^2 ^3 container.18 with minecraft:air
item replace block ^-16 ^2 ^3 container.19 with minecraft:air
item replace block ^-16 ^2 ^3 container.20 with minecraft:air
item replace block ^-16 ^2 ^3 container.21 with minecraft:air
item replace block ^-16 ^2 ^3 container.22 with minecraft:air
item replace block ^-16 ^2 ^3 container.23 with minecraft:air
item replace block ^-16 ^2 ^3 container.24 with minecraft:air
item replace block ^-16 ^2 ^3 container.25 with minecraft:air
item replace block ^-16 ^2 ^3 container.26 with minecraft:air
item replace block ^-16 ^2 ^4 container.0 with minecraft:air
item replace block ^-16 ^2 ^4 container.1 with minecraft:air
item replace block ^-16 ^2 ^4 container.2 with minecraft:air
item replace block ^-16 ^2 ^4 container.3 with minecraft:air
item replace block ^-16 ^2 ^4 container.4 with minecraft:air
item replace block ^-16 ^2 ^4 container.5 with minecraft:air
item replace block ^-16 ^2 ^4 container.6 with minecraft:air
item replace block ^-16 ^2 ^4 container.7 with minecraft:air
item replace block ^-16 ^2 ^4 container.8 with minecraft:air
item replace block ^-16 ^2 ^4 container.9 with minecraft:air
item replace block ^-16 ^2 ^4 container.10 with minecraft:air
item replace block ^-16 ^2 ^4 container.11 with minecraft:air
item replace block ^-16 ^2 ^4 container.12 with minecraft:air
item replace block ^-16 ^2 ^4 container.13 with minecraft:air
item replace block ^-16 ^2 ^4 container.14 with minecraft:air
item replace block ^-16 ^2 ^4 container.15 with minecraft:air
item replace block ^-16 ^2 ^4 container.16 with minecraft:air
item replace block ^-16 ^2 ^4 container.17 with minecraft:air
item replace block ^-16 ^2 ^4 container.18 with minecraft:air
item replace block ^-16 ^2 ^4 container.19 with minecraft:air
item replace block ^-16 ^2 ^4 container.20 with minecraft:air
item replace block ^-16 ^2 ^4 container.21 with minecraft:air
item replace block ^-16 ^2 ^4 container.22 with minecraft:air
item replace block ^-16 ^2 ^4 container.23 with minecraft:air
item replace block ^-16 ^2 ^4 container.24 with minecraft:air
item replace block ^-16 ^2 ^4 container.25 with minecraft:air
item replace block ^-16 ^2 ^4 container.26 with minecraft:air
item replace block ^-17 ^2 ^3 container.0 with minecraft:air
item replace block ^-17 ^2 ^3 container.1 with minecraft:air
item replace block ^-17 ^2 ^3 container.2 with minecraft:air
item replace block ^-17 ^2 ^3 container.3 with minecraft:air
item replace block ^-17 ^2 ^3 container.4 with minecraft:air
item replace block ^-17 ^2 ^3 container.5 with minecraft:air
item replace block ^-17 ^2 ^3 container.6 with minecraft:air
item replace block ^-17 ^2 ^3 container.7 with minecraft:air
item replace block ^-17 ^2 ^3 container.8 with minecraft:air
item replace block ^-17 ^2 ^3 container.9 with minecraft:air
item replace block ^-17 ^2 ^3 container.10 with minecraft:air
item replace block ^-17 ^2 ^3 container.11 with minecraft:air
item replace block ^-17 ^2 ^3 container.12 with minecraft:air
item replace block ^-17 ^2 ^3 container.13 with minecraft:air
item replace block ^-17 ^2 ^3 container.14 with minecraft:air
item replace block ^-17 ^2 ^3 container.15 with minecraft:air
item replace block ^-17 ^2 ^3 container.16 with minecraft:air
item replace block ^-17 ^2 ^3 container.17 with minecraft:air
item replace block ^-17 ^2 ^3 container.18 with minecraft:air
item replace block ^-17 ^2 ^3 container.19 with minecraft:air
item replace block ^-17 ^2 ^3 container.20 with minecraft:air
item replace block ^-17 ^2 ^3 container.21 with minecraft:air
item replace block ^-17 ^2 ^3 container.22 with minecraft:air
item replace block ^-17 ^2 ^3 container.23 with minecraft:air
item replace block ^-17 ^2 ^3 container.24 with minecraft:air
item replace block ^-17 ^2 ^3 container.25 with minecraft:air
item replace block ^-17 ^2 ^3 container.26 with minecraft:air
item replace block ^-17 ^2 ^4 container.0 with minecraft:air
item replace block ^-17 ^2 ^4 container.1 with minecraft:air
item replace block ^-17 ^2 ^4 container.2 with minecraft:air
item replace block ^-17 ^2 ^4 container.3 with minecraft:air
item replace block ^-17 ^2 ^4 container.4 with minecraft:air
item replace block ^-17 ^2 ^4 container.5 with minecraft:air
item replace block ^-17 ^2 ^4 container.6 with minecraft:air
item replace block ^-17 ^2 ^4 container.7 with minecraft:air
item replace block ^-17 ^2 ^4 container.8 with minecraft:air
item replace block ^-17 ^2 ^4 container.9 with minecraft:air
item replace block ^-17 ^2 ^4 container.10 with minecraft:air
item replace block ^-17 ^2 ^4 container.11 with minecraft:air
item replace block ^-17 ^2 ^4 container.12 with minecraft:air
item replace block ^-17 ^2 ^4 container.13 with minecraft:air
item replace block ^-17 ^2 ^4 container.14 with minecraft:air
item replace block ^-17 ^2 ^4 container.15 with minecraft:air
item replace block ^-17 ^2 ^4 container.16 with minecraft:air
item replace block ^-17 ^2 ^4 container.17 with minecraft:air
item replace block ^-17 ^2 ^4 container.18 with minecraft:air
item replace block ^-17 ^2 ^4 container.19 with minecraft:air
item replace block ^-17 ^2 ^4 container.20 with minecraft:air
item replace block ^-17 ^2 ^4 container.21 with minecraft:air
item replace block ^-17 ^2 ^4 container.22 with minecraft:air
item replace block ^-17 ^2 ^4 container.23 with minecraft:air
item replace block ^-17 ^2 ^4 container.24 with minecraft:air
item replace block ^-17 ^2 ^4 container.25 with minecraft:air
item replace block ^-17 ^2 ^4 container.26 with minecraft:air
item replace block ^-18 ^2 ^3 container.0 with minecraft:air
item replace block ^-18 ^2 ^3 container.1 with minecraft:air
item replace block ^-18 ^2 ^3 container.2 with minecraft:air
item replace block ^-18 ^2 ^3 container.3 with minecraft:air
item replace block ^-18 ^2 ^3 container.4 with minecraft:air
item replace block ^-18 ^2 ^3 container.5 with minecraft:air
item replace block ^-18 ^2 ^3 container.6 with minecraft:air
item replace block ^-18 ^2 ^3 container.7 with minecraft:air
item replace block ^-18 ^2 ^3 container.8 with minecraft:air
item replace block ^-18 ^2 ^3 container.9 with minecraft:air
item replace block ^-18 ^2 ^3 container.10 with minecraft:air
item replace block ^-18 ^2 ^3 container.11 with minecraft:air
item replace block ^-18 ^2 ^3 container.12 with minecraft:air
item replace block ^-18 ^2 ^3 container.13 with minecraft:air
item replace block ^-18 ^2 ^3 container.14 with minecraft:air
item replace block ^-18 ^2 ^3 container.15 with minecraft:air
item replace block ^-18 ^2 ^3 container.16 with minecraft:air
item replace block ^-18 ^2 ^3 container.17 with minecraft:air
item replace block ^-18 ^2 ^3 container.18 with minecraft:air
item replace block ^-18 ^2 ^3 container.19 with minecraft:air
item replace block ^-18 ^2 ^3 container.20 with minecraft:air
item replace block ^-18 ^2 ^3 container.21 with minecraft:air
item replace block ^-18 ^2 ^3 container.22 with minecraft:air
item replace block ^-18 ^2 ^3 container.23 with minecraft:air
item replace block ^-18 ^2 ^3 container.24 with minecraft:air
item replace block ^-18 ^2 ^3 container.25 with minecraft:air
item replace block ^-18 ^2 ^3 container.26 with minecraft:air
item replace block ^-18 ^2 ^4 container.0 with minecraft:air
item replace block ^-18 ^2 ^4 container.1 with minecraft:air
item replace block ^-18 ^2 ^4 container.2 with minecraft:air
item replace block ^-18 ^2 ^4 container.3 with minecraft:air
item replace block ^-18 ^2 ^4 container.4 with minecraft:air
item replace block ^-18 ^2 ^4 container.5 with minecraft:air
item replace block ^-18 ^2 ^4 container.6 with minecraft:air
item replace block ^-18 ^2 ^4 container.7 with minecraft:air
item replace block ^-18 ^2 ^4 container.8 with minecraft:air
item replace block ^-18 ^2 ^4 container.9 with minecraft:air
item replace block ^-18 ^2 ^4 container.10 with minecraft:air
item replace block ^-18 ^2 ^4 container.11 with minecraft:air
item replace block ^-18 ^2 ^4 container.12 with minecraft:air
item replace block ^-18 ^2 ^4 container.13 with minecraft:air
item replace block ^-18 ^2 ^4 container.14 with minecraft:air
item replace block ^-18 ^2 ^4 container.15 with minecraft:air
item replace block ^-18 ^2 ^4 container.16 with minecraft:air
item replace block ^-18 ^2 ^4 container.17 with minecraft:air
item replace block ^-18 ^2 ^4 container.18 with minecraft:air
item replace block ^-18 ^2 ^4 container.19 with minecraft:air
item replace block ^-18 ^2 ^4 container.20 with minecraft:air
item replace block ^-18 ^2 ^4 container.21 with minecraft:air
item replace block ^-18 ^2 ^4 container.22 with minecraft:air
item replace block ^-18 ^2 ^4 container.23 with minecraft:air
item replace block ^-18 ^2 ^4 container.24 with minecraft:air
item replace block ^-18 ^2 ^4 container.25 with minecraft:air
item replace block ^-18 ^2 ^4 container.26 with minecraft:air
item replace block ^-19 ^2 ^3 container.0 with minecraft:air
item replace block ^-19 ^2 ^3 container.1 with minecraft:air
item replace block ^-19 ^2 ^3 container.2 with minecraft:air
item replace block ^-19 ^2 ^3 container.3 with minecraft:air
item replace block ^-19 ^2 ^3 container.4 with minecraft:air
item replace block ^-19 ^2 ^3 container.5 with minecraft:air
item replace block ^-19 ^2 ^3 container.6 with minecraft:air
item replace block ^-19 ^2 ^3 container.7 with minecraft:air
item replace block ^-19 ^2 ^3 container.8 with minecraft:air
item replace block ^-19 ^2 ^3 container.9 with minecraft:air
item replace block ^-19 ^2 ^3 container.10 with minecraft:air
item replace block ^-19 ^2 ^3 container.11 with minecraft:air
item replace block ^-19 ^2 ^3 container.12 with minecraft:air
item replace block ^-19 ^2 ^3 container.13 with minecraft:air
item replace block ^-19 ^2 ^3 container.14 with minecraft:air
item replace block ^-19 ^2 ^3 container.15 with minecraft:air
item replace block ^-19 ^2 ^3 container.16 with minecraft:air
item replace block ^-19 ^2 ^3 container.17 with minecraft:air
item replace block ^-19 ^2 ^3 container.18 with minecraft:air
item replace block ^-19 ^2 ^3 container.19 with minecraft:air
item replace block ^-19 ^2 ^3 container.20 with minecraft:air
item replace block ^-19 ^2 ^3 container.21 with minecraft:air
item replace block ^-19 ^2 ^3 container.22 with minecraft:air
item replace block ^-19 ^2 ^3 container.23 with minecraft:air
item replace block ^-19 ^2 ^3 container.24 with minecraft:air
item replace block ^-19 ^2 ^3 container.25 with minecraft:air
item replace block ^-19 ^2 ^3 container.26 with minecraft:air
item replace block ^-19 ^2 ^4 container.0 with minecraft:air
item replace block ^-19 ^2 ^4 container.1 with minecraft:air
item replace block ^-19 ^2 ^4 container.2 with minecraft:air
item replace block ^-19 ^2 ^4 container.3 with minecraft:air
item replace block ^-19 ^2 ^4 container.4 with minecraft:air
item replace block ^-19 ^2 ^4 container.5 with minecraft:air
item replace block ^-19 ^2 ^4 container.6 with minecraft:air
item replace block ^-19 ^2 ^4 container.7 with minecraft:air
item replace block ^-19 ^2 ^4 container.8 with minecraft:air
item replace block ^-19 ^2 ^4 container.9 with minecraft:air
item replace block ^-19 ^2 ^4 container.10 with minecraft:air
item replace block ^-19 ^2 ^4 container.11 with minecraft:air
item replace block ^-19 ^2 ^4 container.12 with minecraft:air
item replace block ^-19 ^2 ^4 container.13 with minecraft:air
item replace block ^-19 ^2 ^4 container.14 with minecraft:air
item replace block ^-19 ^2 ^4 container.15 with minecraft:air
item replace block ^-19 ^2 ^4 container.16 with minecraft:air
item replace block ^-19 ^2 ^4 container.17 with minecraft:air
item replace block ^-19 ^2 ^4 container.18 with minecraft:air
item replace block ^-19 ^2 ^4 container.19 with minecraft:air
item replace block ^-19 ^2 ^4 container.20 with minecraft:air
item replace block ^-19 ^2 ^4 container.21 with minecraft:air
item replace block ^-19 ^2 ^4 container.22 with minecraft:air
item replace block ^-19 ^2 ^4 container.23 with minecraft:air
item replace block ^-19 ^2 ^4 container.24 with minecraft:air
item replace block ^-19 ^2 ^4 container.25 with minecraft:air
item replace block ^-19 ^2 ^4 container.26 with minecraft:air
item replace block ^-20 ^2 ^3 container.0 with minecraft:air
item replace block ^-20 ^2 ^3 container.1 with minecraft:air
item replace block ^-20 ^2 ^3 container.2 with minecraft:air
item replace block ^-20 ^2 ^3 container.3 with minecraft:air
item replace block ^-20 ^2 ^3 container.4 with minecraft:air
item replace block ^-20 ^2 ^3 container.5 with minecraft:air
item replace block ^-20 ^2 ^3 container.6 with minecraft:air
item replace block ^-20 ^2 ^3 container.7 with minecraft:air
item replace block ^-20 ^2 ^3 container.8 with minecraft:air
item replace block ^-20 ^2 ^3 container.9 with minecraft:air
item replace block ^-20 ^2 ^3 container.10 with minecraft:air
item replace block ^-20 ^2 ^3 container.11 with minecraft:air
item replace block ^-20 ^2 ^3 container.12 with minecraft:air
item replace block ^-20 ^2 ^3 container.13 with minecraft:air
item replace block ^-20 ^2 ^3 container.14 with minecraft:air
item replace block ^-20 ^2 ^3 container.15 with minecraft:air
item replace block ^-20 ^2 ^3 container.16 with minecraft:air
item replace block ^-20 ^2 ^3 container.17 with minecraft:air
item replace block ^-20 ^2 ^3 container.18 with minecraft:air
item replace block ^-20 ^2 ^3 container.19 with minecraft:air
item replace block ^-20 ^2 ^3 container.20 with minecraft:air
item replace block ^-20 ^2 ^3 container.21 with minecraft:air
item replace block ^-20 ^2 ^3 container.22 with minecraft:air
item replace block ^-20 ^2 ^3 container.23 with minecraft:air
item replace block ^-20 ^2 ^3 container.24 with minecraft:air
item replace block ^-20 ^2 ^3 container.25 with minecraft:air
item replace block ^-20 ^2 ^3 container.26 with minecraft:air
item replace block ^-20 ^2 ^4 container.0 with minecraft:air
item replace block ^-20 ^2 ^4 container.1 with minecraft:air
item replace block ^-20 ^2 ^4 container.2 with minecraft:air
item replace block ^-20 ^2 ^4 container.3 with minecraft:air
item replace block ^-20 ^2 ^4 container.4 with minecraft:air
item replace block ^-20 ^2 ^4 container.5 with minecraft:air
item replace block ^-20 ^2 ^4 container.6 with minecraft:air
item replace block ^-20 ^2 ^4 container.7 with minecraft:air
item replace block ^-20 ^2 ^4 container.8 with minecraft:air
item replace block ^-20 ^2 ^4 container.9 with minecraft:air
item replace block ^-20 ^2 ^4 container.10 with minecraft:air
item replace block ^-20 ^2 ^4 container.11 with minecraft:air
item replace block ^-20 ^2 ^4 container.12 with minecraft:air
item replace block ^-20 ^2 ^4 container.13 with minecraft:air
item replace block ^-20 ^2 ^4 container.14 with minecraft:air
item replace block ^-20 ^2 ^4 container.15 with minecraft:air
item replace block ^-20 ^2 ^4 container.16 with minecraft:air
item replace block ^-20 ^2 ^4 container.17 with minecraft:air
item replace block ^-20 ^2 ^4 container.18 with minecraft:air
item replace block ^-20 ^2 ^4 container.19 with minecraft:air
item replace block ^-20 ^2 ^4 container.20 with minecraft:air
item replace block ^-20 ^2 ^4 container.21 with minecraft:air
item replace block ^-20 ^2 ^4 container.22 with minecraft:air
item replace block ^-20 ^2 ^4 container.23 with minecraft:air
item replace block ^-20 ^2 ^4 container.24 with minecraft:air
item replace block ^-20 ^2 ^4 container.25 with minecraft:air
item replace block ^-20 ^2 ^4 container.26 with minecraft:air
item replace block ^-21 ^2 ^3 container.0 with minecraft:air
item replace block ^-21 ^2 ^3 container.1 with minecraft:air
item replace block ^-21 ^2 ^3 container.2 with minecraft:air
item replace block ^-21 ^2 ^3 container.3 with minecraft:air
item replace block ^-21 ^2 ^3 container.4 with minecraft:air
item replace block ^-21 ^2 ^3 container.5 with minecraft:air
item replace block ^-21 ^2 ^3 container.6 with minecraft:air
item replace block ^-21 ^2 ^3 container.7 with minecraft:air
item replace block ^-21 ^2 ^3 container.8 with minecraft:air
item replace block ^-21 ^2 ^3 container.9 with minecraft:air
item replace block ^-21 ^2 ^3 container.10 with minecraft:air
item replace block ^-21 ^2 ^3 container.11 with minecraft:air
item replace block ^-21 ^2 ^3 container.12 with minecraft:air
item replace block ^-21 ^2 ^3 container.13 with minecraft:air
item replace block ^-21 ^2 ^3 container.14 with minecraft:air
item replace block ^-21 ^2 ^3 container.15 with minecraft:air
item replace block ^-21 ^2 ^3 container.16 with minecraft:air
item replace block ^-21 ^2 ^3 container.17 with minecraft:air
item replace block ^-21 ^2 ^3 container.18 with minecraft:air
item replace block ^-21 ^2 ^3 container.19 with minecraft:air
item replace block ^-21 ^2 ^3 container.20 with minecraft:air
item replace block ^-21 ^2 ^3 container.21 with minecraft:air
item replace block ^-21 ^2 ^3 container.22 with minecraft:air
item replace block ^-21 ^2 ^3 container.23 with minecraft:air
item replace block ^-21 ^2 ^3 container.24 with minecraft:air
item replace block ^-21 ^2 ^3 container.25 with minecraft:air
item replace block ^-21 ^2 ^3 container.26 with minecraft:air
item replace block ^-21 ^2 ^4 container.0 with minecraft:air
item replace block ^-21 ^2 ^4 container.1 with minecraft:air
item replace block ^-21 ^2 ^4 container.2 with minecraft:air
item replace block ^-21 ^2 ^4 container.3 with minecraft:air
item replace block ^-21 ^2 ^4 container.4 with minecraft:air
item replace block ^-21 ^2 ^4 container.5 with minecraft:air
item replace block ^-21 ^2 ^4 container.6 with minecraft:air
item replace block ^-21 ^2 ^4 container.7 with minecraft:air
item replace block ^-21 ^2 ^4 container.8 with minecraft:air
item replace block ^-21 ^2 ^4 container.9 with minecraft:air
item replace block ^-21 ^2 ^4 container.10 with minecraft:air
item replace block ^-21 ^2 ^4 container.11 with minecraft:air
item replace block ^-21 ^2 ^4 container.12 with minecraft:air
item replace block ^-21 ^2 ^4 container.13 with minecraft:air
item replace block ^-21 ^2 ^4 container.14 with minecraft:air
item replace block ^-21 ^2 ^4 container.15 with minecraft:air
item replace block ^-21 ^2 ^4 container.16 with minecraft:air
item replace block ^-21 ^2 ^4 container.17 with minecraft:air
item replace block ^-21 ^2 ^4 container.18 with minecraft:air
item replace block ^-21 ^2 ^4 container.19 with minecraft:air
item replace block ^-21 ^2 ^4 container.20 with minecraft:air
item replace block ^-21 ^2 ^4 container.21 with minecraft:air
item replace block ^-21 ^2 ^4 container.22 with minecraft:air
item replace block ^-21 ^2 ^4 container.23 with minecraft:air
item replace block ^-21 ^2 ^4 container.24 with minecraft:air
item replace block ^-21 ^2 ^4 container.25 with minecraft:air
item replace block ^-21 ^2 ^4 container.26 with minecraft:air
item replace block ^-22 ^2 ^3 container.0 with minecraft:air
item replace block ^-22 ^2 ^3 container.1 with minecraft:air
item replace block ^-22 ^2 ^3 container.2 with minecraft:air
item replace block ^-22 ^2 ^3 container.3 with minecraft:air
item replace block ^-22 ^2 ^3 container.4 with minecraft:air
item replace block ^-22 ^2 ^3 container.5 with minecraft:air
item replace block ^-22 ^2 ^3 container.6 with minecraft:air
item replace block ^-22 ^2 ^3 container.7 with minecraft:air
item replace block ^-22 ^2 ^3 container.8 with minecraft:air
item replace block ^-22 ^2 ^3 container.9 with minecraft:air
item replace block ^-22 ^2 ^3 container.10 with minecraft:air
item replace block ^-22 ^2 ^3 container.11 with minecraft:air
item replace block ^-22 ^2 ^3 container.12 with minecraft:air
item replace block ^-22 ^2 ^3 container.13 with minecraft:air
item replace block ^-22 ^2 ^3 container.14 with minecraft:air
item replace block ^-22 ^2 ^3 container.15 with minecraft:air
item replace block ^-22 ^2 ^3 container.16 with minecraft:air
item replace block ^-22 ^2 ^3 container.17 with minecraft:air
item replace block ^-22 ^2 ^3 container.18 with minecraft:air
item replace block ^-22 ^2 ^3 container.19 with minecraft:air
item replace block ^-22 ^2 ^3 container.20 with minecraft:air
item replace block ^-22 ^2 ^3 container.21 with minecraft:air
item replace block ^-22 ^2 ^3 container.22 with minecraft:air
item replace block ^-22 ^2 ^3 container.23 with minecraft:air
item replace block ^-22 ^2 ^3 container.24 with minecraft:air
item replace block ^-22 ^2 ^3 container.25 with minecraft:air
item replace block ^-22 ^2 ^3 container.26 with minecraft:air
item replace block ^-22 ^2 ^4 container.0 with minecraft:air
item replace block ^-22 ^2 ^4 container.1 with minecraft:air
item replace block ^-22 ^2 ^4 container.2 with minecraft:air
item replace block ^-22 ^2 ^4 container.3 with minecraft:air
item replace block ^-22 ^2 ^4 container.4 with minecraft:air
item replace block ^-22 ^2 ^4 container.5 with minecraft:air
item replace block ^-22 ^2 ^4 container.6 with minecraft:air
item replace block ^-22 ^2 ^4 container.7 with minecraft:air
item replace block ^-22 ^2 ^4 container.8 with minecraft:air
item replace block ^-22 ^2 ^4 container.9 with minecraft:air
item replace block ^-22 ^2 ^4 container.10 with minecraft:air
item replace block ^-22 ^2 ^4 container.11 with minecraft:air
item replace block ^-22 ^2 ^4 container.12 with minecraft:air
item replace block ^-22 ^2 ^4 container.13 with minecraft:air
item replace block ^-22 ^2 ^4 container.14 with minecraft:air
item replace block ^-22 ^2 ^4 container.15 with minecraft:air
item replace block ^-22 ^2 ^4 container.16 with minecraft:air
item replace block ^-22 ^2 ^4 container.17 with minecraft:air
item replace block ^-22 ^2 ^4 container.18 with minecraft:air
item replace block ^-22 ^2 ^4 container.19 with minecraft:air
item replace block ^-22 ^2 ^4 container.20 with minecraft:air
item replace block ^-22 ^2 ^4 container.21 with minecraft:air
item replace block ^-22 ^2 ^4 container.22 with minecraft:air
item replace block ^-22 ^2 ^4 container.23 with minecraft:air
item replace block ^-22 ^2 ^4 container.24 with minecraft:air
item replace block ^-22 ^2 ^4 container.25 with minecraft:air
item replace block ^-22 ^2 ^4 container.26 with minecraft:air
item replace block ^-23 ^2 ^3 container.0 with minecraft:air
item replace block ^-23 ^2 ^3 container.1 with minecraft:air
item replace block ^-23 ^2 ^3 container.2 with minecraft:air
item replace block ^-23 ^2 ^3 container.3 with minecraft:air
item replace block ^-23 ^2 ^3 container.4 with minecraft:air
item replace block ^-23 ^2 ^3 container.5 with minecraft:air
item replace block ^-23 ^2 ^3 container.6 with minecraft:air
item replace block ^-23 ^2 ^3 container.7 with minecraft:air
item replace block ^-23 ^2 ^3 container.8 with minecraft:air
item replace block ^-23 ^2 ^3 container.9 with minecraft:air
item replace block ^-23 ^2 ^3 container.10 with minecraft:air
item replace block ^-23 ^2 ^3 container.11 with minecraft:air
item replace block ^-23 ^2 ^3 container.12 with minecraft:air
item replace block ^-23 ^2 ^3 container.13 with minecraft:air
item replace block ^-23 ^2 ^3 container.14 with minecraft:air
item replace block ^-23 ^2 ^3 container.15 with minecraft:air
item replace block ^-23 ^2 ^3 container.16 with minecraft:air
item replace block ^-23 ^2 ^3 container.17 with minecraft:air
item replace block ^-23 ^2 ^3 container.18 with minecraft:air
item replace block ^-23 ^2 ^3 container.19 with minecraft:air
item replace block ^-23 ^2 ^3 container.20 with minecraft:air
item replace block ^-23 ^2 ^3 container.21 with minecraft:air
item replace block ^-23 ^2 ^3 container.22 with minecraft:air
item replace block ^-23 ^2 ^3 container.23 with minecraft:air
item replace block ^-23 ^2 ^3 container.24 with minecraft:air
item replace block ^-23 ^2 ^3 container.25 with minecraft:air
item replace block ^-23 ^2 ^3 container.26 with minecraft:air
item replace block ^-23 ^2 ^4 container.0 with minecraft:air
item replace block ^-23 ^2 ^4 container.1 with minecraft:air
item replace block ^-23 ^2 ^4 container.2 with minecraft:air
item replace block ^-23 ^2 ^4 container.3 with minecraft:air
item replace block ^-23 ^2 ^4 container.4 with minecraft:air
item replace block ^-23 ^2 ^4 container.5 with minecraft:air
item replace block ^-23 ^2 ^4 container.6 with minecraft:air
item replace block ^-23 ^2 ^4 container.7 with minecraft:air
item replace block ^-23 ^2 ^4 container.8 with minecraft:air
item replace block ^-23 ^2 ^4 container.9 with minecraft:air
item replace block ^-23 ^2 ^4 container.10 with minecraft:air
item replace block ^-23 ^2 ^4 container.11 with minecraft:air
item replace block ^-23 ^2 ^4 container.12 with minecraft:air
item replace block ^-23 ^2 ^4 container.13 with minecraft:air
item replace block ^-23 ^2 ^4 container.14 with minecraft:air
item replace block ^-23 ^2 ^4 container.15 with minecraft:air
item replace block ^-23 ^2 ^4 container.16 with minecraft:air
item replace block ^-23 ^2 ^4 container.17 with minecraft:air
item replace block ^-23 ^2 ^4 container.18 with minecraft:air
item replace block ^-23 ^2 ^4 container.19 with minecraft:air
item replace block ^-23 ^2 ^4 container.20 with minecraft:air
item replace block ^-23 ^2 ^4 container.21 with minecraft:air
item replace block ^-23 ^2 ^4 container.22 with minecraft:air
item replace block ^-23 ^2 ^4 container.23 with minecraft:air
item replace block ^-23 ^2 ^4 container.24 with minecraft:air
item replace block ^-23 ^2 ^4 container.25 with minecraft:air
item replace block ^-23 ^2 ^4 container.26 with minecraft:air
item replace block ^-24 ^2 ^3 container.0 with minecraft:air
item replace block ^-24 ^2 ^3 container.1 with minecraft:air
item replace block ^-24 ^2 ^3 container.2 with minecraft:air
item replace block ^-24 ^2 ^3 container.3 with minecraft:air
item replace block ^-24 ^2 ^3 container.4 with minecraft:air
item replace block ^-24 ^2 ^3 container.5 with minecraft:air
item replace block ^-24 ^2 ^3 container.6 with minecraft:air
item replace block ^-24 ^2 ^3 container.7 with minecraft:air
item replace block ^-24 ^2 ^3 container.8 with minecraft:air
item replace block ^-24 ^2 ^3 container.9 with minecraft:air
item replace block ^-24 ^2 ^3 container.10 with minecraft:air
item replace block ^-24 ^2 ^3 container.11 with minecraft:air
item replace block ^-24 ^2 ^3 container.12 with minecraft:air
item replace block ^-24 ^2 ^3 container.13 with minecraft:air
item replace block ^-24 ^2 ^3 container.14 with minecraft:air
item replace block ^-24 ^2 ^3 container.15 with minecraft:air
item replace block ^-24 ^2 ^3 container.16 with minecraft:air
item replace block ^-24 ^2 ^3 container.17 with minecraft:air
item replace block ^-24 ^2 ^3 container.18 with minecraft:air
item replace block ^-24 ^2 ^3 container.19 with minecraft:air
item replace block ^-24 ^2 ^3 container.20 with minecraft:air
item replace block ^-24 ^2 ^3 container.21 with minecraft:air
item replace block ^-24 ^2 ^3 container.22 with minecraft:air
item replace block ^-24 ^2 ^3 container.23 with minecraft:air
item replace block ^-24 ^2 ^3 container.24 with minecraft:air
item replace block ^-24 ^2 ^3 container.25 with minecraft:air
item replace block ^-24 ^2 ^3 container.26 with minecraft:air
item replace block ^-24 ^2 ^4 container.0 with minecraft:air
item replace block ^-24 ^2 ^4 container.1 with minecraft:air
item replace block ^-24 ^2 ^4 container.2 with minecraft:air
item replace block ^-24 ^2 ^4 container.3 with minecraft:air
item replace block ^-24 ^2 ^4 container.4 with minecraft:air
item replace block ^-24 ^2 ^4 container.5 with minecraft:air
item replace block ^-24 ^2 ^4 container.6 with minecraft:air
item replace block ^-24 ^2 ^4 container.7 with minecraft:air
item replace block ^-24 ^2 ^4 container.8 with minecraft:air
item replace block ^-24 ^2 ^4 container.9 with minecraft:air
item replace block ^-24 ^2 ^4 container.10 with minecraft:air
item replace block ^-24 ^2 ^4 container.11 with minecraft:air
item replace block ^-24 ^2 ^4 container.12 with minecraft:air
item replace block ^-24 ^2 ^4 container.13 with minecraft:air
item replace block ^-24 ^2 ^4 container.14 with minecraft:air
item replace block ^-24 ^2 ^4 container.15 with minecraft:air
item replace block ^-24 ^2 ^4 container.16 with minecraft:air
item replace block ^-24 ^2 ^4 container.17 with minecraft:air
item replace block ^-24 ^2 ^4 container.18 with minecraft:air
item replace block ^-24 ^2 ^4 container.19 with minecraft:air
item replace block ^-24 ^2 ^4 container.20 with minecraft:air
item replace block ^-24 ^2 ^4 container.21 with minecraft:air
item replace block ^-24 ^2 ^4 container.22 with minecraft:air
item replace block ^-24 ^2 ^4 container.23 with minecraft:air
item replace block ^-24 ^2 ^4 container.24 with minecraft:air
item replace block ^-24 ^2 ^4 container.25 with minecraft:air
item replace block ^-24 ^2 ^4 container.26 with minecraft:air
item replace block ^-25 ^2 ^3 container.0 with minecraft:air
item replace block ^-25 ^2 ^3 container.1 with minecraft:air
item replace block ^-25 ^2 ^3 container.2 with minecraft:air
item replace block ^-25 ^2 ^3 container.3 with minecraft:air
item replace block ^-25 ^2 ^3 container.4 with minecraft:air
item replace block ^-25 ^2 ^3 container.5 with minecraft:air
item replace block ^-25 ^2 ^3 container.6 with minecraft:air
item replace block ^-25 ^2 ^3 container.7 with minecraft:air
item replace block ^-25 ^2 ^3 container.8 with minecraft:air
item replace block ^-25 ^2 ^3 container.9 with minecraft:air
item replace block ^-25 ^2 ^3 container.10 with minecraft:air
item replace block ^-25 ^2 ^3 container.11 with minecraft:air
item replace block ^-25 ^2 ^3 container.12 with minecraft:air
item replace block ^-25 ^2 ^3 container.13 with minecraft:air
item replace block ^-25 ^2 ^3 container.14 with minecraft:air
item replace block ^-25 ^2 ^3 container.15 with minecraft:air
item replace block ^-25 ^2 ^3 container.16 with minecraft:air
item replace block ^-25 ^2 ^3 container.17 with minecraft:air
item replace block ^-25 ^2 ^3 container.18 with minecraft:air
item replace block ^-25 ^2 ^3 container.19 with minecraft:air
item replace block ^-25 ^2 ^3 container.20 with minecraft:air
item replace block ^-25 ^2 ^3 container.21 with minecraft:air
item replace block ^-25 ^2 ^3 container.22 with minecraft:air
item replace block ^-25 ^2 ^3 container.23 with minecraft:air
item replace block ^-25 ^2 ^3 container.24 with minecraft:air
item replace block ^-25 ^2 ^3 container.25 with minecraft:air
item replace block ^-25 ^2 ^3 container.26 with minecraft:air
item replace block ^-25 ^2 ^4 container.0 with minecraft:air
item replace block ^-25 ^2 ^4 container.1 with minecraft:air
item replace block ^-25 ^2 ^4 container.2 with minecraft:air
item replace block ^-25 ^2 ^4 container.3 with minecraft:air
item replace block ^-25 ^2 ^4 container.4 with minecraft:air
item replace block ^-25 ^2 ^4 container.5 with minecraft:air
item replace block ^-25 ^2 ^4 container.6 with minecraft:air
item replace block ^-25 ^2 ^4 container.7 with minecraft:air
item replace block ^-25 ^2 ^4 container.8 with minecraft:air
item replace block ^-25 ^2 ^4 container.9 with minecraft:air
item replace block ^-25 ^2 ^4 container.10 with minecraft:air
item replace block ^-25 ^2 ^4 container.11 with minecraft:air
item replace block ^-25 ^2 ^4 container.12 with minecraft:air
item replace block ^-25 ^2 ^4 container.13 with minecraft:air
item replace block ^-25 ^2 ^4 container.14 with minecraft:air
item replace block ^-25 ^2 ^4 container.15 with minecraft:air
item replace block ^-25 ^2 ^4 container.16 with minecraft:air
item replace block ^-25 ^2 ^4 container.17 with minecraft:air
item replace block ^-25 ^2 ^4 container.18 with minecraft:air
item replace block ^-25 ^2 ^4 container.19 with minecraft:air
item replace block ^-25 ^2 ^4 container.20 with minecraft:air
item replace block ^-25 ^2 ^4 container.21 with minecraft:air
item replace block ^-25 ^2 ^4 container.22 with minecraft:air
item replace block ^-25 ^2 ^4 container.23 with minecraft:air
item replace block ^-25 ^2 ^4 container.24 with minecraft:air
item replace block ^-25 ^2 ^4 container.25 with minecraft:air
item replace block ^-25 ^2 ^4 container.26 with minecraft:air
