item replace block ~ ~-1 ~0 container.0 with minecraft:air
item replace block ~ ~-1 ~0 container.1 with minecraft:air
item replace block ~ ~-1 ~0 container.2 with minecraft:air
item replace block ~ ~-1 ~0 container.3 with minecraft:air
item replace block ~ ~-1 ~0 container.4 with minecraft:air
item replace block ~ ~-1 ~0 container.5 with minecraft:air
item replace block ~ ~-1 ~0 container.6 with minecraft:air
item replace block ~ ~-1 ~0 container.7 with minecraft:air
item replace block ~ ~-1 ~0 container.8 with minecraft:air
item replace block ~ ~-1 ~0 container.9 with minecraft:air
item replace block ~ ~-1 ~0 container.10 with minecraft:air
item replace block ~ ~-1 ~0 container.11 with minecraft:air
item replace block ~ ~-1 ~0 container.12 with minecraft:air
item replace block ~ ~-1 ~0 container.13 with minecraft:air
item replace block ~ ~-1 ~0 container.14 with minecraft:air
item replace block ~ ~-1 ~0 container.15 with minecraft:air
item replace block ~ ~-1 ~0 container.16 with minecraft:air
item replace block ~ ~-1 ~0 container.17 with minecraft:air
item replace block ~ ~-1 ~0 container.18 with minecraft:air
item replace block ~ ~-1 ~0 container.19 with minecraft:air
item replace block ~ ~-1 ~0 container.20 with minecraft:air
item replace block ~ ~-1 ~0 container.21 with minecraft:air
item replace block ~ ~-1 ~0 container.22 with minecraft:air
item replace block ~ ~-1 ~0 container.23 with minecraft:air
item replace block ~ ~-1 ~0 container.24 with minecraft:air
item replace block ~ ~-1 ~0 container.25 with minecraft:air
item replace block ~ ~-1 ~0 container.26 with minecraft:air