item replace block ^-1 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-1 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-1 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-1 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-1 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-1 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-2 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-2 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-2 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-2 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-2 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-2 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-3 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-3 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-3 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-3 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-3 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-3 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-4 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-4 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-4 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-4 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-4 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-4 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-5 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-5 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-5 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-5 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-5 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-5 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-6 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-6 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-6 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-6 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-6 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-6 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-7 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-7 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-7 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-7 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-7 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-7 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-8 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-8 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-8 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-8 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-8 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-8 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-9 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-9 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-9 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-9 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-9 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-9 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-10 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-10 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-10 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-10 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-10 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-10 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-11 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-11 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-11 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-11 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-11 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-11 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-12 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-12 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-12 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-12 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-12 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-12 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-13 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-13 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-13 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-13 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-13 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-13 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-14 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-14 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-14 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-14 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-14 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-14 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-15 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-15 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-15 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-15 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-15 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-15 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-16 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-16 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-16 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-16 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-16 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-16 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-17 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-17 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-17 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-17 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-17 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-17 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-18 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-18 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-18 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-18 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-18 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-18 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-19 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-19 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-19 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-19 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-19 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-19 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-20 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-20 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-20 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-20 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-20 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-20 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-21 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-21 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-21 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-21 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-21 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-21 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-22 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-22 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-22 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-22 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-22 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-22 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-23 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-23 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-23 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-23 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-23 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-23 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-24 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-24 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-24 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-24 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-24 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-24 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-25 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-25 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-25 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-25 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-25 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-25 ^2 ^3 container.5 with minecraft:glass 10
