item replace block ^-1 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-1 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-1 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-1 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-1 ^2 ^3 container.4 with minecraft:glass 52
item replace block ^-1 ^2 ^3 container.5 with minecraft:shears 1
item replace block ^-1 ^2 ^3 container.6 with minecraft:white_stained_glass 14
item replace block ^-1 ^2 ^3 container.7 with minecraft:shears 1
item replace block ^-1 ^2 ^3 container.8 with minecraft:orange_stained_glass 6
item replace block ^-2 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-2 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-2 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-2 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-2 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-2 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-3 ^2 ^3 container.0 with minecraft:glass 17
item replace block ^-3 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-3 ^2 ^3 container.2 with minecraft:white_stained_glass 64
item replace block ^-3 ^2 ^3 container.3 with minecraft:white_stained_glass 64
item replace block ^-3 ^2 ^3 container.4 with minecraft:white_stained_glass 64
item replace block ^-3 ^2 ^3 container.5 with minecraft:white_stained_glass 64
item replace block ^-3 ^2 ^3 container.6 with minecraft:white_stained_glass 18
item replace block ^-3 ^2 ^3 container.7 with minecraft:shears 1
item replace block ^-3 ^2 ^3 container.8 with minecraft:orange_stained_glass 26
item replace block ^-3 ^2 ^3 container.9 with minecraft:shears 1
item replace block ^-3 ^2 ^3 container.10 with minecraft:magenta_stained_glass 1
item replace block ^-3 ^2 ^3 container.11 with minecraft:shears 1
item replace block ^-3 ^2 ^3 container.12 with minecraft:shears 1
item replace block ^-3 ^2 ^3 container.13 with minecraft:light_blue_stained_glass 7
item replace block ^-4 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-4 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-4 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-4 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-4 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-4 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-5 ^2 ^3 container.0 with minecraft:glass 49
item replace block ^-5 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-5 ^2 ^3 container.2 with minecraft:white_stained_glass 64
item replace block ^-5 ^2 ^3 container.3 with minecraft:white_stained_glass 64
item replace block ^-5 ^2 ^3 container.4 with minecraft:white_stained_glass 64
item replace block ^-5 ^2 ^3 container.5 with minecraft:white_stained_glass 46
item replace block ^-5 ^2 ^3 container.6 with minecraft:shears 1
item replace block ^-5 ^2 ^3 container.7 with minecraft:orange_stained_glass 8
item replace block ^-5 ^2 ^3 container.8 with minecraft:shears 1
item replace block ^-5 ^2 ^3 container.9 with minecraft:magenta_stained_glass 5
item replace block ^-5 ^2 ^3 container.10 with minecraft:shears 1
item replace block ^-5 ^2 ^3 container.11 with minecraft:light_blue_stained_glass 5
item replace block ^-5 ^2 ^3 container.12 with minecraft:shears 1
item replace block ^-5 ^2 ^3 container.13 with minecraft:yellow_stained_glass 20
item replace block ^-6 ^2 ^3 container.0 with minecraft:glass 53
item replace block ^-6 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-6 ^2 ^3 container.2 with minecraft:white_stained_glass 25
item replace block ^-6 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-6 ^2 ^3 container.4 with minecraft:orange_stained_glass 64
item replace block ^-6 ^2 ^3 container.5 with minecraft:orange_stained_glass 64
item replace block ^-6 ^2 ^3 container.6 with minecraft:orange_stained_glass 64
item replace block ^-6 ^2 ^3 container.7 with minecraft:orange_stained_glass 21
item replace block ^-6 ^2 ^3 container.8 with minecraft:shears 1
item replace block ^-6 ^2 ^3 container.9 with minecraft:magenta_stained_glass 8
item replace block ^-6 ^2 ^3 container.10 with minecraft:shears 1
item replace block ^-6 ^2 ^3 container.11 with minecraft:light_blue_stained_glass 8
item replace block ^-6 ^2 ^3 container.12 with minecraft:shears 1
item replace block ^-6 ^2 ^3 container.13 with minecraft:yellow_stained_glass 6
item replace block ^-6 ^2 ^3 container.14 with minecraft:shears 1
item replace block ^-6 ^2 ^3 container.15 with minecraft:lime_stained_glass 1
item replace block ^-6 ^2 ^3 container.16 with minecraft:shears 1
item replace block ^-6 ^2 ^3 container.17 with minecraft:pink_stained_glass 9
item replace block ^-7 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-7 ^2 ^3 container.1 with minecraft:glass 25
item replace block ^-7 ^2 ^3 container.2 with minecraft:shears 1
item replace block ^-7 ^2 ^3 container.3 with minecraft:white_stained_glass 64
item replace block ^-7 ^2 ^3 container.4 with minecraft:white_stained_glass 64
item replace block ^-7 ^2 ^3 container.5 with minecraft:white_stained_glass 64
item replace block ^-7 ^2 ^3 container.6 with minecraft:white_stained_glass 2
item replace block ^-7 ^2 ^3 container.7 with minecraft:shears 1
item replace block ^-7 ^2 ^3 container.8 with minecraft:orange_stained_glass 45
item replace block ^-8 ^2 ^3 container.0 with minecraft:glass 19
item replace block ^-8 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-8 ^2 ^3 container.2 with minecraft:white_stained_glass 64
item replace block ^-8 ^2 ^3 container.3 with minecraft:white_stained_glass 64
item replace block ^-8 ^2 ^3 container.4 with minecraft:shears 1
item replace block ^-8 ^2 ^3 container.5 with minecraft:orange_stained_glass 64
item replace block ^-8 ^2 ^3 container.6 with minecraft:orange_stained_glass 64
item replace block ^-8 ^2 ^3 container.7 with minecraft:orange_stained_glass 3
item replace block ^-8 ^2 ^3 container.8 with minecraft:shears 1
item replace block ^-8 ^2 ^3 container.9 with minecraft:magenta_stained_glass 14
item replace block ^-8 ^2 ^3 container.10 with minecraft:shears 1
item replace block ^-8 ^2 ^3 container.11 with minecraft:shears 1
item replace block ^-8 ^2 ^3 container.12 with minecraft:light_blue_stained_glass 10
item replace block ^-8 ^2 ^3 container.13 with minecraft:shears 1
item replace block ^-8 ^2 ^3 container.14 with minecraft:yellow_stained_glass 2
item replace block ^-8 ^2 ^3 container.15 with minecraft:shears 1
item replace block ^-8 ^2 ^3 container.16 with minecraft:lime_stained_glass 19
item replace block ^-9 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-9 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-9 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-9 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-9 ^2 ^3 container.4 with minecraft:glass 14
item replace block ^-9 ^2 ^3 container.5 with minecraft:shears 1
item replace block ^-9 ^2 ^3 container.6 with minecraft:white_stained_glass 15
item replace block ^-9 ^2 ^3 container.7 with minecraft:shears 1
item replace block ^-9 ^2 ^3 container.8 with minecraft:orange_stained_glass 2
item replace block ^-9 ^2 ^3 container.9 with minecraft:shears 1
item replace block ^-9 ^2 ^3 container.10 with minecraft:magenta_stained_glass 40
item replace block ^-10 ^2 ^3 container.0 with minecraft:glass 51
item replace block ^-10 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-10 ^2 ^3 container.2 with minecraft:white_stained_glass 64
item replace block ^-10 ^2 ^3 container.3 with minecraft:white_stained_glass 1
item replace block ^-10 ^2 ^3 container.4 with minecraft:shears 1
item replace block ^-10 ^2 ^3 container.5 with minecraft:orange_stained_glass 28
item replace block ^-10 ^2 ^3 container.6 with minecraft:shears 1
item replace block ^-10 ^2 ^3 container.7 with minecraft:magenta_stained_glass 8
item replace block ^-10 ^2 ^3 container.8 with minecraft:shears 1
item replace block ^-10 ^2 ^3 container.9 with minecraft:light_blue_stained_glass 64
item replace block ^-10 ^2 ^3 container.10 with minecraft:light_blue_stained_glass 64
item replace block ^-10 ^2 ^3 container.11 with minecraft:light_blue_stained_glass 1
item replace block ^-10 ^2 ^3 container.12 with minecraft:shears 1
item replace block ^-10 ^2 ^3 container.13 with minecraft:yellow_stained_glass 5
item replace block ^-10 ^2 ^3 container.14 with minecraft:shears 1
item replace block ^-10 ^2 ^3 container.15 with minecraft:lime_stained_glass 2
item replace block ^-10 ^2 ^3 container.16 with minecraft:shears 1
item replace block ^-10 ^2 ^3 container.17 with minecraft:pink_stained_glass 10
item replace block ^-10 ^2 ^3 container.18 with minecraft:shears 1
item replace block ^-10 ^2 ^3 container.19 with minecraft:shears 1
item replace block ^-10 ^2 ^3 container.20 with minecraft:gray_stained_glass 23
item replace block ^-11 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-11 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-11 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-11 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-11 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-11 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-12 ^2 ^3 container.0 with minecraft:glass 7
item replace block ^-12 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.2 with minecraft:white_stained_glass 47
item replace block ^-12 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.4 with minecraft:orange_stained_glass 3
item replace block ^-12 ^2 ^3 container.5 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.6 with minecraft:magenta_stained_glass 31
item replace block ^-12 ^2 ^3 container.7 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.8 with minecraft:light_blue_stained_glass 57
item replace block ^-12 ^2 ^3 container.9 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.10 with minecraft:yellow_stained_glass 64
item replace block ^-12 ^2 ^3 container.11 with minecraft:yellow_stained_glass 55
item replace block ^-12 ^2 ^3 container.12 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.13 with minecraft:lime_stained_glass 7
item replace block ^-12 ^2 ^3 container.14 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.15 with minecraft:pink_stained_glass 3
item replace block ^-12 ^2 ^3 container.16 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.17 with minecraft:gray_stained_glass 5
item replace block ^-12 ^2 ^3 container.18 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.19 with minecraft:light_gray_stained_glass 2
item replace block ^-12 ^2 ^3 container.20 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.21 with minecraft:cyan_stained_glass 22
item replace block ^-12 ^2 ^3 container.22 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.23 with minecraft:purple_stained_glass 15
item replace block ^-12 ^2 ^3 container.24 with minecraft:shears 1
item replace block ^-13 ^2 ^3 container.0 with minecraft:glass 5
item replace block ^-13 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-13 ^2 ^3 container.2 with minecraft:white_stained_glass 64
item replace block ^-13 ^2 ^3 container.3 with minecraft:white_stained_glass 3
item replace block ^-13 ^2 ^3 container.4 with minecraft:shears 1
item replace block ^-13 ^2 ^3 container.5 with minecraft:orange_stained_glass 64
item replace block ^-13 ^2 ^3 container.6 with minecraft:orange_stained_glass 5
item replace block ^-13 ^2 ^3 container.7 with minecraft:shears 1
item replace block ^-13 ^2 ^3 container.8 with minecraft:magenta_stained_glass 1
item replace block ^-13 ^2 ^3 container.9 with minecraft:shears 1
item replace block ^-13 ^2 ^3 container.10 with minecraft:light_blue_stained_glass 8
item replace block ^-13 ^2 ^3 container.11 with minecraft:shears 1
item replace block ^-13 ^2 ^3 container.12 with minecraft:yellow_stained_glass 64
item replace block ^-13 ^2 ^3 container.13 with minecraft:yellow_stained_glass 64
item replace block ^-13 ^2 ^3 container.14 with minecraft:shears 1
item replace block ^-13 ^2 ^3 container.15 with minecraft:lime_stained_glass 20
item replace block ^-13 ^2 ^3 container.16 with minecraft:shears 1
item replace block ^-13 ^2 ^3 container.17 with minecraft:pink_stained_glass 25
item replace block ^-14 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-14 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-14 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-14 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-14 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-14 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-15 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-15 ^2 ^3 container.1 with minecraft:glass 17
item replace block ^-15 ^2 ^3 container.2 with minecraft:shears 1
item replace block ^-15 ^2 ^3 container.3 with minecraft:white_stained_glass 49
item replace block ^-15 ^2 ^3 container.4 with minecraft:shears 1
item replace block ^-15 ^2 ^3 container.5 with minecraft:orange_stained_glass 9
item replace block ^-15 ^2 ^3 container.6 with minecraft:shears 1
item replace block ^-15 ^2 ^3 container.7 with minecraft:magenta_stained_glass 8
item replace block ^-15 ^2 ^3 container.8 with minecraft:shears 1
item replace block ^-15 ^2 ^3 container.9 with minecraft:light_blue_stained_glass 64
item replace block ^-15 ^2 ^3 container.10 with minecraft:light_blue_stained_glass 64
item replace block ^-15 ^2 ^3 container.11 with minecraft:light_blue_stained_glass 3
item replace block ^-15 ^2 ^3 container.12 with minecraft:shears 1
item replace block ^-15 ^2 ^3 container.13 with minecraft:yellow_stained_glass 29
item replace block ^-15 ^2 ^3 container.14 with minecraft:shears 1
item replace block ^-15 ^2 ^3 container.15 with minecraft:lime_stained_glass 17
item replace block ^-16 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-16 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-16 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-16 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-16 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-16 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-17 ^2 ^3 container.0 with minecraft:glass 61
item replace block ^-17 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-17 ^2 ^3 container.2 with minecraft:white_stained_glass 64
item replace block ^-17 ^2 ^3 container.3 with minecraft:white_stained_glass 3
item replace block ^-17 ^2 ^3 container.4 with minecraft:shears 1
item replace block ^-17 ^2 ^3 container.5 with minecraft:orange_stained_glass 64
item replace block ^-17 ^2 ^3 container.6 with minecraft:orange_stained_glass 64
item replace block ^-17 ^2 ^3 container.7 with minecraft:orange_stained_glass 64
item replace block ^-17 ^2 ^3 container.8 with minecraft:orange_stained_glass 8
item replace block ^-18 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-18 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-18 ^2 ^3 container.2 with minecraft:glass 23
item replace block ^-18 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-18 ^2 ^3 container.4 with minecraft:white_stained_glass 64
item replace block ^-18 ^2 ^3 container.5 with minecraft:white_stained_glass 64
item replace block ^-18 ^2 ^3 container.6 with minecraft:white_stained_glass 50
item replace block ^-19 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-19 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-19 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-19 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-19 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-19 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-20 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-20 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-20 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-20 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-20 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-20 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-21 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-21 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-21 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-21 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-21 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-21 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-22 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-22 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-22 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-22 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-22 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-22 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-23 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-23 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-23 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-23 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-23 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-23 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-24 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-24 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-24 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-24 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-24 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-24 ^2 ^3 container.5 with minecraft:glass 10
item replace block ^-25 ^2 ^3 container.0 with minecraft:glass 64
item replace block ^-25 ^2 ^3 container.1 with minecraft:glass 64
item replace block ^-25 ^2 ^3 container.2 with minecraft:glass 64
item replace block ^-25 ^2 ^3 container.3 with minecraft:glass 64
item replace block ^-25 ^2 ^3 container.4 with minecraft:glass 64
item replace block ^-25 ^2 ^3 container.5 with minecraft:glass 10
