item replace block ^-0 ^0 ^3 container.0 with minecraft:shears 1
item replace block ^-0 ^0 ^3 container.1 with minecraft:dirt 64
item replace block ^-0 ^0 ^3 container.2 with minecraft:dirt 31
item replace block ^-0 ^0 ^3 container.3 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.0 with minecraft:dirt 1
item replace block ^-1 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.2 with minecraft:dirt 4
item replace block ^-1 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.4 with minecraft:dirt 39
item replace block ^-1 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.6 with minecraft:dirt 2
item replace block ^-1 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.8 with minecraft:dirt 4
item replace block ^-1 ^-1 ^3 container.9 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.10 with minecraft:dirt 40
item replace block ^-1 ^-1 ^3 container.11 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.12 with minecraft:dirt 1
item replace block ^-3 ^-1 ^3 container.0 with minecraft:dirt 2
item replace block ^-3 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.2 with minecraft:dirt 4
item replace block ^-3 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.4 with minecraft:dirt 4
item replace block ^-3 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.6 with minecraft:dirt 35
item replace block ^-3 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.8 with minecraft:dirt 45
item replace block ^-3 ^-1 ^3 container.9 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.10 with minecraft:dirt 2
item replace block ^-5 ^-1 ^3 container.0 with minecraft:dirt 5
item replace block ^-5 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.2 with minecraft:dirt 2
item replace block ^-5 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.4 with minecraft:dirt 4
item replace block ^-5 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.6 with minecraft:dirt 4
item replace block ^-5 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.8 with minecraft:dirt 64
item replace block ^-5 ^-1 ^3 container.9 with minecraft:dirt 5
item replace block ^-5 ^-1 ^3 container.10 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.11 with minecraft:dirt 4
item replace block ^-5 ^-1 ^3 container.12 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.13 with minecraft:dirt 3
item replace block ^-7 ^0 ^3 container.0 with minecraft:dirt 3
item replace block ^-7 ^0 ^3 container.1 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.2 with minecraft:dirt 7
item replace block ^-7 ^0 ^3 container.3 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.4 with minecraft:dirt 2
item replace block ^-7 ^0 ^3 container.5 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.6 with minecraft:dirt 4
item replace block ^-7 ^0 ^3 container.7 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.8 with minecraft:dirt 4
item replace block ^-7 ^0 ^3 container.9 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.10 with minecraft:dirt 57
item replace block ^-7 ^0 ^3 container.11 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.12 with minecraft:dirt 4
item replace block ^-7 ^0 ^3 container.13 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.14 with minecraft:dirt 9
item replace block ^-8 ^-1 ^3 container.0 with minecraft:dirt 4
item replace block ^-8 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.2 with minecraft:dirt 4
item replace block ^-8 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.4 with minecraft:dirt 7
item replace block ^-8 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.6 with minecraft:dirt 2
item replace block ^-8 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.8 with minecraft:dirt 4
item replace block ^-8 ^-1 ^3 container.9 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.10 with minecraft:dirt 50
item replace block ^-8 ^-1 ^3 container.11 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.12 with minecraft:dirt 4
item replace block ^-8 ^-1 ^3 container.13 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.14 with minecraft:dirt 7
item replace block ^-8 ^-1 ^3 container.15 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.16 with minecraft:dirt 2
item replace block ^-8 ^-1 ^3 container.17 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.18 with minecraft:dirt 4
item replace block ^-12 ^0 ^3 container.0 with minecraft:dirt 10
item replace block ^-12 ^0 ^3 container.1 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.2 with minecraft:dirt 4
item replace block ^-12 ^0 ^3 container.3 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.4 with minecraft:dirt 7
item replace block ^-12 ^0 ^3 container.5 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.6 with minecraft:dirt 2
item replace block ^-12 ^0 ^3 container.7 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.8 with minecraft:dirt 3
item replace block ^-12 ^0 ^3 container.9 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.10 with minecraft:dirt 39
item replace block ^-12 ^0 ^3 container.11 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.12 with minecraft:dirt 4
item replace block ^-12 ^0 ^3 container.13 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.14 with minecraft:dirt 7
item replace block ^-12 ^0 ^3 container.15 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.16 with minecraft:dirt 2
item replace block ^-12 ^0 ^3 container.17 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.18 with minecraft:dirt 4
item replace block ^-12 ^0 ^3 container.19 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.20 with minecraft:dirt 5
item replace block ^-13 ^-1 ^3 container.0 with minecraft:dirt 16
item replace block ^-13 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-13 ^-1 ^3 container.2 with minecraft:dirt 4
item replace block ^-13 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-13 ^-1 ^3 container.4 with minecraft:dirt 7
item replace block ^-13 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-13 ^-1 ^3 container.6 with minecraft:dirt 1
item replace block ^-13 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-13 ^-1 ^3 container.8 with minecraft:dirt 4
item replace block ^-13 ^-1 ^3 container.9 with minecraft:shears 1
item replace block ^-13 ^-1 ^3 container.10 with minecraft:dirt 27
item replace block ^-13 ^-1 ^3 container.11 with minecraft:shears 1
item replace block ^-13 ^-1 ^3 container.12 with minecraft:dirt 4
item replace block ^-13 ^-1 ^3 container.13 with minecraft:shears 1
item replace block ^-13 ^-1 ^3 container.14 with minecraft:dirt 7
item replace block ^-13 ^-1 ^3 container.15 with minecraft:shears 1
item replace block ^-13 ^-1 ^3 container.16 with minecraft:dirt 2
item replace block ^-13 ^-1 ^3 container.17 with minecraft:shears 1
item replace block ^-13 ^-1 ^3 container.18 with minecraft:dirt 4
item replace block ^-13 ^-1 ^3 container.19 with minecraft:shears 1
item replace block ^-13 ^-1 ^3 container.20 with minecraft:dirt 4
item replace block ^-13 ^-1 ^3 container.21 with minecraft:shears 1
item replace block ^-13 ^-1 ^3 container.22 with minecraft:dirt 6
item replace block ^-15 ^-1 ^3 container.0 with minecraft:dirt 22
item replace block ^-15 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.2 with minecraft:dirt 4
item replace block ^-15 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.4 with minecraft:dirt 4
item replace block ^-15 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.6 with minecraft:dirt 4
item replace block ^-15 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.8 with minecraft:dirt 4
item replace block ^-15 ^-1 ^3 container.9 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.10 with minecraft:dirt 15
item replace block ^-15 ^-1 ^3 container.11 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.12 with minecraft:dirt 4
item replace block ^-15 ^-1 ^3 container.13 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.14 with minecraft:dirt 7
item replace block ^-15 ^-1 ^3 container.15 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.16 with minecraft:dirt 2
item replace block ^-15 ^-1 ^3 container.17 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.18 with minecraft:dirt 4
item replace block ^-15 ^-1 ^3 container.19 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.20 with minecraft:dirt 4
item replace block ^-15 ^-1 ^3 container.21 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.22 with minecraft:dirt 12
item replace block ^-17 ^-1 ^3 container.0 with minecraft:dirt 28
item replace block ^-17 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.2 with minecraft:dirt 6
item replace block ^-17 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.4 with minecraft:dirt 2
item replace block ^-17 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.6 with minecraft:dirt 4
item replace block ^-17 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.8 with minecraft:dirt 8
item replace block ^-17 ^-1 ^3 container.9 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.10 with minecraft:dirt 4
item replace block ^-17 ^-1 ^3 container.11 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.12 with minecraft:dirt 7
item replace block ^-17 ^-1 ^3 container.13 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.14 with minecraft:dirt 2
item replace block ^-17 ^-1 ^3 container.15 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.16 with minecraft:dirt 4
item replace block ^-17 ^-1 ^3 container.17 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.18 with minecraft:dirt 4
item replace block ^-17 ^-1 ^3 container.19 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.20 with minecraft:dirt 18
item replace block ^-19 ^0 ^3 container.0 with minecraft:dirt 33
item replace block ^-19 ^0 ^3 container.1 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.2 with minecraft:dirt 7
item replace block ^-19 ^0 ^3 container.3 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.4 with minecraft:dirt 2
item replace block ^-19 ^0 ^3 container.5 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.6 with minecraft:dirt 6
item replace block ^-19 ^0 ^3 container.7 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.8 with minecraft:dirt 7
item replace block ^-19 ^0 ^3 container.9 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.10 with minecraft:dirt 2
item replace block ^-19 ^0 ^3 container.11 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.12 with minecraft:dirt 4
item replace block ^-19 ^0 ^3 container.13 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.14 with minecraft:dirt 4
item replace block ^-19 ^0 ^3 container.15 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.16 with minecraft:dirt 24
item replace block ^-20 ^-1 ^3 container.0 with minecraft:dirt 34
item replace block ^-20 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-20 ^-1 ^3 container.2 with minecraft:dirt 4
item replace block ^-20 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-20 ^-1 ^3 container.4 with minecraft:dirt 7
item replace block ^-20 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-20 ^-1 ^3 container.6 with minecraft:dirt 5
item replace block ^-20 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-20 ^-1 ^3 container.8 with minecraft:dirt 2
item replace block ^-20 ^-1 ^3 container.9 with minecraft:shears 1
item replace block ^-20 ^-1 ^3 container.10 with minecraft:dirt 4
item replace block ^-20 ^-1 ^3 container.11 with minecraft:shears 1
item replace block ^-20 ^-1 ^3 container.12 with minecraft:dirt 4
item replace block ^-20 ^-1 ^3 container.13 with minecraft:shears 1
item replace block ^-20 ^-1 ^3 container.14 with minecraft:dirt 30
item replace block ^-24 ^0 ^3 container.0 with minecraft:dirt 40
item replace block ^-24 ^0 ^3 container.1 with minecraft:shears 1
item replace block ^-24 ^0 ^3 container.2 with minecraft:dirt 4
item replace block ^-24 ^0 ^3 container.3 with minecraft:shears 1
item replace block ^-24 ^0 ^3 container.4 with minecraft:dirt 4
item replace block ^-24 ^0 ^3 container.5 with minecraft:shears 1
item replace block ^-24 ^0 ^3 container.6 with minecraft:dirt 4
item replace block ^-24 ^0 ^3 container.7 with minecraft:shears 1
item replace block ^-24 ^0 ^3 container.8 with minecraft:dirt 4
item replace block ^-24 ^0 ^3 container.9 with minecraft:shears 1
item replace block ^-24 ^0 ^3 container.10 with minecraft:dirt 36
