item replace block ^-1 ^-1 ^3 container.0 with minecraft:dirt 4
item replace block ^-1 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.2 with minecraft:dirt 23
item replace block ^-1 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.4 with minecraft:dirt 23
item replace block ^-1 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.6 with minecraft:dirt 23
item replace block ^-1 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.8 with minecraft:dirt 19
item replace block ^-3 ^-1 ^3 container.0 with minecraft:dirt 10
item replace block ^-3 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.2 with minecraft:dirt 23
item replace block ^-3 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.4 with minecraft:dirt 23
item replace block ^-3 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.6 with minecraft:dirt 23
item replace block ^-3 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.8 with minecraft:dirt 13
item replace block ^-5 ^-1 ^3 container.0 with minecraft:dirt 18
item replace block ^-5 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.2 with minecraft:dirt 23
item replace block ^-5 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.4 with minecraft:dirt 23
item replace block ^-5 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.6 with minecraft:dirt 23
item replace block ^-5 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.8 with minecraft:dirt 5
item replace block ^-7 ^0 ^3 container.0 with minecraft:dirt 2
item replace block ^-7 ^0 ^3 container.1 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.2 with minecraft:dirt 5
item replace block ^-7 ^0 ^3 container.3 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.4 with minecraft:dirt 8
item replace block ^-7 ^0 ^3 container.5 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.6 with minecraft:dirt 1
item replace block ^-7 ^0 ^3 container.7 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.8 with minecraft:dirt 6
item replace block ^-7 ^0 ^3 container.9 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.10 with minecraft:dirt 5
item replace block ^-7 ^0 ^3 container.11 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.12 with minecraft:dirt 8
item replace block ^-7 ^0 ^3 container.13 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.14 with minecraft:dirt 1
item replace block ^-7 ^0 ^3 container.15 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.16 with minecraft:dirt 6
item replace block ^-7 ^0 ^3 container.17 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.18 with minecraft:dirt 5
item replace block ^-7 ^0 ^3 container.19 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.20 with minecraft:dirt 8
item replace block ^-7 ^0 ^3 container.21 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.22 with minecraft:dirt 1
item replace block ^-7 ^0 ^3 container.23 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.24 with minecraft:dirt 6
item replace block ^-7 ^0 ^3 container.25 with minecraft:shears 1
item replace block ^-7 ^0 ^3 container.26 with minecraft:dirt 5
item replace block ^-7 ^0 ^4 container.0 with minecraft:shears 1
item replace block ^-7 ^0 ^4 container.1 with minecraft:dirt 8
item replace block ^-7 ^0 ^4 container.2 with minecraft:shears 1
item replace block ^-7 ^0 ^4 container.3 with minecraft:dirt 1
item replace block ^-7 ^0 ^4 container.4 with minecraft:shears 1
item replace block ^-7 ^0 ^4 container.5 with minecraft:dirt 4
item replace block ^-8 ^-1 ^3 container.0 with minecraft:dirt 1
item replace block ^-8 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.2 with minecraft:dirt 1
item replace block ^-8 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.4 with minecraft:dirt 3
item replace block ^-8 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.6 with minecraft:dirt 1
item replace block ^-8 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.8 with minecraft:dirt 6
item replace block ^-8 ^-1 ^3 container.9 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.10 with minecraft:dirt 3
item replace block ^-8 ^-1 ^3 container.11 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.12 with minecraft:dirt 4
item replace block ^-8 ^-1 ^3 container.13 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.14 with minecraft:dirt 1
item replace block ^-8 ^-1 ^3 container.15 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.16 with minecraft:dirt 3
item replace block ^-8 ^-1 ^3 container.17 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.18 with minecraft:dirt 1
item replace block ^-8 ^-1 ^3 container.19 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.20 with minecraft:dirt 6
item replace block ^-8 ^-1 ^3 container.21 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.22 with minecraft:dirt 3
item replace block ^-8 ^-1 ^3 container.23 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.24 with minecraft:dirt 4
item replace block ^-8 ^-1 ^3 container.25 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.26 with minecraft:dirt 1
item replace block ^-8 ^-1 ^4 container.0 with minecraft:shears 1
item replace block ^-8 ^-1 ^4 container.1 with minecraft:dirt 3
item replace block ^-8 ^-1 ^4 container.2 with minecraft:shears 1
item replace block ^-8 ^-1 ^4 container.3 with minecraft:dirt 1
item replace block ^-8 ^-1 ^4 container.4 with minecraft:shears 1
item replace block ^-8 ^-1 ^4 container.5 with minecraft:dirt 6
item replace block ^-8 ^-1 ^4 container.6 with minecraft:shears 1
item replace block ^-8 ^-1 ^4 container.7 with minecraft:dirt 3
item replace block ^-8 ^-1 ^4 container.8 with minecraft:shears 1
item replace block ^-8 ^-1 ^4 container.9 with minecraft:dirt 4
item replace block ^-8 ^-1 ^4 container.10 with minecraft:shears 1
item replace block ^-8 ^-1 ^4 container.11 with minecraft:dirt 1
item replace block ^-8 ^-1 ^4 container.12 with minecraft:shears 1
item replace block ^-8 ^-1 ^4 container.13 with minecraft:dirt 3
item replace block ^-8 ^-1 ^4 container.14 with minecraft:shears 1
item replace block ^-8 ^-1 ^4 container.15 with minecraft:dirt 1
item replace block ^-8 ^-1 ^4 container.16 with minecraft:shears 1
item replace block ^-8 ^-1 ^4 container.17 with minecraft:dirt 6
item replace block ^-8 ^-1 ^4 container.18 with minecraft:shears 1
item replace block ^-8 ^-1 ^4 container.19 with minecraft:dirt 3
item replace block ^-8 ^-1 ^4 container.20 with minecraft:shears 1
item replace block ^-8 ^-1 ^4 container.21 with minecraft:dirt 3
item replace block ^-12 ^0 ^3 container.0 with minecraft:dirt 15
item replace block ^-12 ^0 ^3 container.1 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.2 with minecraft:dirt 5
item replace block ^-12 ^0 ^3 container.3 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.4 with minecraft:dirt 17
item replace block ^-12 ^0 ^3 container.5 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.6 with minecraft:dirt 5
item replace block ^-12 ^0 ^3 container.7 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.8 with minecraft:dirt 17
item replace block ^-12 ^0 ^3 container.9 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.10 with minecraft:dirt 5
item replace block ^-12 ^0 ^3 container.11 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.12 with minecraft:dirt 17
item replace block ^-12 ^0 ^3 container.13 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.14 with minecraft:dirt 5
item replace block ^-12 ^0 ^3 container.15 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.16 with minecraft:dirt 2
item replace block ^-15 ^-1 ^3 container.0 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.1 with minecraft:dirt 5
item replace block ^-15 ^-1 ^3 container.2 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.3 with minecraft:dirt 7
item replace block ^-15 ^-1 ^3 container.4 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.5 with minecraft:dirt 9
item replace block ^-15 ^-1 ^3 container.6 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.7 with minecraft:dirt 5
item replace block ^-15 ^-1 ^3 container.8 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.9 with minecraft:dirt 7
item replace block ^-15 ^-1 ^3 container.10 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.11 with minecraft:dirt 9
item replace block ^-15 ^-1 ^3 container.12 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.13 with minecraft:dirt 5
item replace block ^-15 ^-1 ^3 container.14 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.15 with minecraft:dirt 7
item replace block ^-15 ^-1 ^3 container.16 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.17 with minecraft:dirt 9
item replace block ^-15 ^-1 ^3 container.18 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.19 with minecraft:dirt 5
item replace block ^-15 ^-1 ^3 container.20 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.21 with minecraft:dirt 7
item replace block ^-15 ^-1 ^3 container.22 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.23 with minecraft:dirt 9
item replace block ^-17 ^-1 ^3 container.0 with minecraft:dirt 5
item replace block ^-17 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.2 with minecraft:dirt 17
item replace block ^-17 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.4 with minecraft:dirt 5
item replace block ^-17 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.6 with minecraft:dirt 17
item replace block ^-17 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.8 with minecraft:dirt 5
item replace block ^-17 ^-1 ^3 container.9 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.10 with minecraft:dirt 17
item replace block ^-17 ^-1 ^3 container.11 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.12 with minecraft:dirt 5
item replace block ^-17 ^-1 ^3 container.13 with minecraft:shears 1
item replace block ^-17 ^-1 ^3 container.14 with minecraft:dirt 17
item replace block ^-17 ^-1 ^3 container.15 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.0 with minecraft:dirt 11
item replace block ^-19 ^0 ^3 container.1 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.2 with minecraft:dirt 1
item replace block ^-19 ^0 ^3 container.3 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.4 with minecraft:dirt 21
item replace block ^-19 ^0 ^3 container.5 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.6 with minecraft:dirt 23
item replace block ^-19 ^0 ^3 container.7 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.8 with minecraft:dirt 1
item replace block ^-19 ^0 ^3 container.9 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.10 with minecraft:dirt 21
item replace block ^-19 ^0 ^3 container.11 with minecraft:shears 1
item replace block ^-19 ^0 ^3 container.12 with minecraft:dirt 12
item replace block ^-20 ^-1 ^3 container.0 with minecraft:dirt 12
item replace block ^-20 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-20 ^-1 ^3 container.2 with minecraft:dirt 24
item replace block ^-20 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-20 ^-1 ^3 container.4 with minecraft:dirt 22
item replace block ^-20 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-20 ^-1 ^3 container.6 with minecraft:dirt 24
item replace block ^-20 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-20 ^-1 ^3 container.8 with minecraft:dirt 10
item replace block ^-22 ^-1 ^3 container.0 with minecraft:dirt 36
item replace block ^-22 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-22 ^-1 ^3 container.2 with minecraft:dirt 47
item replace block ^-22 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-22 ^-1 ^3 container.4 with minecraft:dirt 11
