item replace block ^-8 ^-1 ^3 container.0 with minecraft:dirt 2
item replace block ^-8 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.2 with minecraft:dirt 23
item replace block ^-8 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.4 with minecraft:dirt 23
item replace block ^-8 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.6 with minecraft:dirt 23
item replace block ^-8 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.8 with minecraft:dirt 21
item replace block ^-10 ^-1 ^3 container.0 with minecraft:dirt 8
item replace block ^-10 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-10 ^-1 ^3 container.2 with minecraft:dirt 1
item replace block ^-10 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-10 ^-1 ^3 container.4 with minecraft:dirt 21
item replace block ^-10 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-10 ^-1 ^3 container.6 with minecraft:dirt 1
item replace block ^-10 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-10 ^-1 ^3 container.8 with minecraft:dirt 21
item replace block ^-10 ^-1 ^3 container.9 with minecraft:shears 1
item replace block ^-10 ^-1 ^3 container.10 with minecraft:dirt 1
item replace block ^-10 ^-1 ^3 container.11 with minecraft:shears 1
item replace block ^-10 ^-1 ^3 container.12 with minecraft:dirt 21
item replace block ^-10 ^-1 ^3 container.13 with minecraft:shears 1
item replace block ^-10 ^-1 ^3 container.14 with minecraft:dirt 1
item replace block ^-10 ^-1 ^3 container.15 with minecraft:shears 1
item replace block ^-10 ^-1 ^3 container.16 with minecraft:dirt 13
item replace block ^-12 ^0 ^3 container.0 with minecraft:dirt 14
item replace block ^-12 ^0 ^3 container.1 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.2 with minecraft:dirt 1
item replace block ^-12 ^0 ^3 container.3 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.4 with minecraft:dirt 1
item replace block ^-12 ^0 ^3 container.5 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.6 with minecraft:dirt 3
item replace block ^-12 ^0 ^3 container.7 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.8 with minecraft:dirt 15
item replace block ^-12 ^0 ^3 container.9 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.10 with minecraft:dirt 1
item replace block ^-12 ^0 ^3 container.11 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.12 with minecraft:dirt 1
item replace block ^-12 ^0 ^3 container.13 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.14 with minecraft:dirt 3
item replace block ^-12 ^0 ^3 container.15 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.16 with minecraft:dirt 15
item replace block ^-12 ^0 ^3 container.17 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.18 with minecraft:dirt 1
item replace block ^-12 ^0 ^3 container.19 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.20 with minecraft:dirt 1
item replace block ^-12 ^0 ^3 container.21 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.22 with minecraft:dirt 3
item replace block ^-12 ^0 ^3 container.23 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.24 with minecraft:dirt 15
item replace block ^-12 ^0 ^3 container.25 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.26 with minecraft:dirt 1
item replace block ^-12 ^0 ^4 container.0 with minecraft:shears 1
item replace block ^-12 ^0 ^4 container.1 with minecraft:dirt 1
item replace block ^-12 ^0 ^4 container.2 with minecraft:shears 1
item replace block ^-12 ^0 ^4 container.3 with minecraft:dirt 3
item replace block ^-12 ^0 ^4 container.4 with minecraft:shears 1
item replace block ^-12 ^0 ^4 container.5 with minecraft:dirt 1
