item replace block ^-0 ^0 ^3 container.0 with minecraft:dirt 23
item replace block ^-0 ^0 ^3 container.1 with minecraft:shears 1
item replace block ^-0 ^0 ^3 container.2 with minecraft:dirt 23
item replace block ^-0 ^0 ^3 container.3 with minecraft:shears 1
item replace block ^-0 ^0 ^3 container.4 with minecraft:dirt 23
item replace block ^-0 ^0 ^3 container.5 with minecraft:shears 1
item replace block ^-0 ^0 ^3 container.6 with minecraft:dirt 23
item replace block ^-0 ^0 ^3 container.7 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.0 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.1 with minecraft:dirt 23
item replace block ^-1 ^-1 ^3 container.2 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.3 with minecraft:dirt 23
item replace block ^-1 ^-1 ^3 container.4 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.5 with minecraft:dirt 23
item replace block ^-1 ^-1 ^3 container.6 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.7 with minecraft:dirt 23
item replace block ^-3 ^-1 ^3 container.0 with minecraft:dirt 6
item replace block ^-3 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.2 with minecraft:dirt 23
item replace block ^-3 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.4 with minecraft:dirt 23
item replace block ^-3 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.6 with minecraft:dirt 23
item replace block ^-3 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.8 with minecraft:dirt 17
item replace block ^-5 ^-1 ^3 container.0 with minecraft:dirt 12
item replace block ^-5 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.2 with minecraft:dirt 23
item replace block ^-5 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.4 with minecraft:dirt 23
item replace block ^-5 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.6 with minecraft:dirt 23
item replace block ^-5 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.8 with minecraft:dirt 11
item replace block ^-8 ^-1 ^3 container.0 with minecraft:dirt 2
item replace block ^-8 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.2 with minecraft:dirt 19
item replace block ^-8 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.4 with minecraft:dirt 3
item replace block ^-8 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.6 with minecraft:dirt 19
item replace block ^-8 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.8 with minecraft:dirt 3
item replace block ^-8 ^-1 ^3 container.9 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.10 with minecraft:dirt 19
item replace block ^-8 ^-1 ^3 container.11 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.12 with minecraft:dirt 3
item replace block ^-8 ^-1 ^3 container.13 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.14 with minecraft:dirt 19
item replace block ^-8 ^-1 ^3 container.15 with minecraft:shears 1
item replace block ^-8 ^-1 ^3 container.16 with minecraft:dirt 1
item replace block ^-10 ^-1 ^3 container.0 with minecraft:dirt 8
item replace block ^-10 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-10 ^-1 ^3 container.2 with minecraft:dirt 23
item replace block ^-10 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-10 ^-1 ^3 container.4 with minecraft:dirt 23
item replace block ^-10 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-10 ^-1 ^3 container.6 with minecraft:dirt 23
item replace block ^-10 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-10 ^-1 ^3 container.8 with minecraft:dirt 15
item replace block ^-12 ^0 ^3 container.0 with minecraft:dirt 14
item replace block ^-12 ^0 ^3 container.1 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.2 with minecraft:dirt 6
item replace block ^-12 ^0 ^3 container.3 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.4 with minecraft:dirt 16
item replace block ^-12 ^0 ^3 container.5 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.6 with minecraft:dirt 6
item replace block ^-12 ^0 ^3 container.7 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.8 with minecraft:dirt 16
item replace block ^-12 ^0 ^3 container.9 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.10 with minecraft:dirt 6
item replace block ^-12 ^0 ^3 container.11 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.12 with minecraft:dirt 16
item replace block ^-12 ^0 ^3 container.13 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.14 with minecraft:dirt 6
item replace block ^-12 ^0 ^3 container.15 with minecraft:shears 1
item replace block ^-12 ^0 ^3 container.16 with minecraft:dirt 2
item replace block ^-15 ^-1 ^3 container.0 with minecraft:dirt 20
item replace block ^-15 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.2 with minecraft:dirt 23
item replace block ^-15 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.4 with minecraft:dirt 23
item replace block ^-15 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.6 with minecraft:dirt 23
item replace block ^-15 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-15 ^-1 ^3 container.8 with minecraft:dirt 3
