item replace block ^-0 ^0 ^3 container.0 with minecraft:dirt 48
item replace block ^-0 ^0 ^3 container.1 with minecraft:shears 1
item replace block ^-0 ^0 ^3 container.2 with minecraft:dirt 24
item replace block ^-0 ^0 ^3 container.3 with minecraft:shears 1
item replace block ^-0 ^0 ^3 container.4 with minecraft:dirt 24
item replace block ^-1 ^-1 ^3 container.0 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.1 with minecraft:dirt 23
item replace block ^-1 ^-1 ^3 container.2 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.3 with minecraft:dirt 24
item replace block ^-1 ^-1 ^3 container.4 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.5 with minecraft:dirt 24
item replace block ^-1 ^-1 ^3 container.6 with minecraft:shears 1
item replace block ^-1 ^-1 ^3 container.7 with minecraft:dirt 23
item replace block ^-3 ^-1 ^3 container.0 with minecraft:dirt 6
item replace block ^-3 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.2 with minecraft:dirt 23
item replace block ^-3 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.4 with minecraft:dirt 24
item replace block ^-3 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.6 with minecraft:dirt 24
item replace block ^-3 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-3 ^-1 ^3 container.8 with minecraft:dirt 17
item replace block ^-5 ^-1 ^3 container.0 with minecraft:dirt 12
item replace block ^-5 ^-1 ^3 container.1 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.2 with minecraft:dirt 23
item replace block ^-5 ^-1 ^3 container.3 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.4 with minecraft:dirt 24
item replace block ^-5 ^-1 ^3 container.5 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.6 with minecraft:dirt 24
item replace block ^-5 ^-1 ^3 container.7 with minecraft:shears 1
item replace block ^-5 ^-1 ^3 container.8 with minecraft:dirt 11
