item replace block ^-1 ^2 ^3 container.0 with minecraft:glass 47
item replace block ^-2 ^2 ^3 container.0 with minecraft:glass 40
item replace block ^-2 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-2 ^2 ^3 container.2 with minecraft:white_stained_glass 4
item replace block ^-2 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-2 ^2 ^3 container.4 with minecraft:orange_stained_glass 1
item replace block ^-3 ^2 ^3 container.0 with minecraft:glass 39
item replace block ^-3 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-3 ^2 ^3 container.2 with minecraft:white_stained_glass 3
item replace block ^-3 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-3 ^2 ^3 container.4 with minecraft:orange_stained_glass 2
item replace block ^-3 ^2 ^3 container.5 with minecraft:shears 1
item replace block ^-4 ^2 ^3 container.0 with minecraft:glass 47
item replace block ^-5 ^2 ^3 container.0 with minecraft:glass 38
item replace block ^-5 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-5 ^2 ^3 container.2 with minecraft:white_stained_glass 5
item replace block ^-5 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-5 ^2 ^3 container.4 with minecraft:shears 1
item replace block ^-5 ^2 ^3 container.5 with minecraft:orange_stained_glass 1
item replace block ^-6 ^2 ^3 container.0 with minecraft:glass 47
item replace block ^-7 ^2 ^3 container.0 with minecraft:glass 37
item replace block ^-7 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-7 ^2 ^3 container.2 with minecraft:white_stained_glass 5
item replace block ^-7 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-7 ^2 ^3 container.4 with minecraft:orange_stained_glass 3
item replace block ^-8 ^2 ^3 container.0 with minecraft:glass 36
item replace block ^-8 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-8 ^2 ^3 container.2 with minecraft:white_stained_glass 7
item replace block ^-8 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-8 ^2 ^3 container.4 with minecraft:orange_stained_glass 2
item replace block ^-9 ^2 ^3 container.0 with minecraft:glass 11
item replace block ^-9 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-9 ^2 ^3 container.2 with minecraft:white_stained_glass 21
item replace block ^-9 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-9 ^2 ^3 container.4 with minecraft:orange_stained_glass 13
item replace block ^-10 ^2 ^3 container.0 with minecraft:glass 34
item replace block ^-10 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-10 ^2 ^3 container.2 with minecraft:white_stained_glass 7
item replace block ^-10 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-10 ^2 ^3 container.4 with minecraft:shears 1
item replace block ^-10 ^2 ^3 container.5 with minecraft:orange_stained_glass 1
item replace block ^-10 ^2 ^3 container.6 with minecraft:shears 1
item replace block ^-10 ^2 ^3 container.7 with minecraft:magenta_stained_glass 1
item replace block ^-11 ^2 ^3 container.0 with minecraft:glass 31
item replace block ^-11 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-11 ^2 ^3 container.2 with minecraft:white_stained_glass 15
item replace block ^-12 ^2 ^3 container.0 with minecraft:glass 29
item replace block ^-12 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.2 with minecraft:white_stained_glass 2
item replace block ^-12 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.4 with minecraft:orange_stained_glass 8
item replace block ^-12 ^2 ^3 container.5 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.6 with minecraft:magenta_stained_glass 2
item replace block ^-12 ^2 ^3 container.7 with minecraft:shears 1
item replace block ^-12 ^2 ^3 container.8 with minecraft:light_blue_stained_glass 2
item replace block ^-13 ^2 ^3 container.0 with minecraft:glass 47
item replace block ^-14 ^2 ^3 container.0 with minecraft:glass 10
item replace block ^-14 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-14 ^2 ^3 container.2 with minecraft:white_stained_glass 1
item replace block ^-14 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-14 ^2 ^3 container.4 with minecraft:orange_stained_glass 6
item replace block ^-14 ^2 ^3 container.5 with minecraft:shears 1
item replace block ^-14 ^2 ^3 container.6 with minecraft:magenta_stained_glass 2
item replace block ^-14 ^2 ^3 container.7 with minecraft:shears 1
item replace block ^-14 ^2 ^3 container.8 with minecraft:shears 1
item replace block ^-14 ^2 ^3 container.9 with minecraft:light_blue_stained_glass 3
item replace block ^-14 ^2 ^3 container.10 with minecraft:shears 1
item replace block ^-14 ^2 ^3 container.11 with minecraft:yellow_stained_glass 2
item replace block ^-14 ^2 ^3 container.12 with minecraft:shears 1
item replace block ^-14 ^2 ^3 container.13 with minecraft:lime_stained_glass 9
item replace block ^-14 ^2 ^3 container.14 with minecraft:shears 1
item replace block ^-14 ^2 ^3 container.15 with minecraft:pink_stained_glass 6
item replace block ^-15 ^2 ^3 container.0 with minecraft:glass 8
item replace block ^-15 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-15 ^2 ^3 container.2 with minecraft:white_stained_glass 4
item replace block ^-15 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-15 ^2 ^3 container.4 with minecraft:orange_stained_glass 6
item replace block ^-15 ^2 ^3 container.5 with minecraft:shears 1
item replace block ^-15 ^2 ^3 container.6 with minecraft:shears 1
item replace block ^-15 ^2 ^3 container.7 with minecraft:magenta_stained_glass 6
item replace block ^-15 ^2 ^3 container.8 with minecraft:shears 1
item replace block ^-15 ^2 ^3 container.9 with minecraft:light_blue_stained_glass 10
item replace block ^-15 ^2 ^3 container.10 with minecraft:shears 1
item replace block ^-15 ^2 ^3 container.11 with minecraft:yellow_stained_glass 7
item replace block ^-16 ^2 ^3 container.0 with minecraft:glass 25
item replace block ^-16 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-16 ^2 ^3 container.2 with minecraft:white_stained_glass 21
item replace block ^-17 ^2 ^3 container.0 with minecraft:glass 6
item replace block ^-17 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-17 ^2 ^3 container.2 with minecraft:white_stained_glass 2
item replace block ^-17 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-17 ^2 ^3 container.4 with minecraft:orange_stained_glass 4
item replace block ^-17 ^2 ^3 container.5 with minecraft:shears 1
item replace block ^-17 ^2 ^3 container.6 with minecraft:magenta_stained_glass 7
item replace block ^-17 ^2 ^3 container.7 with minecraft:shears 1
item replace block ^-17 ^2 ^3 container.8 with minecraft:shears 1
item replace block ^-17 ^2 ^3 container.9 with minecraft:light_blue_stained_glass 2
item replace block ^-17 ^2 ^3 container.10 with minecraft:shears 1
item replace block ^-17 ^2 ^3 container.11 with minecraft:yellow_stained_glass 11
item replace block ^-17 ^2 ^3 container.12 with minecraft:shears 1
item replace block ^-17 ^2 ^3 container.13 with minecraft:lime_stained_glass 8
item replace block ^-18 ^2 ^3 container.0 with minecraft:glass 47
item replace block ^-19 ^2 ^3 container.0 with minecraft:glass 4
item replace block ^-19 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-19 ^2 ^3 container.2 with minecraft:white_stained_glass 2
item replace block ^-19 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-19 ^2 ^3 container.4 with minecraft:orange_stained_glass 7
item replace block ^-19 ^2 ^3 container.5 with minecraft:shears 1
item replace block ^-19 ^2 ^3 container.6 with minecraft:magenta_stained_glass 5
item replace block ^-19 ^2 ^3 container.7 with minecraft:shears 1
item replace block ^-19 ^2 ^3 container.8 with minecraft:light_blue_stained_glass 2
item replace block ^-19 ^2 ^3 container.9 with minecraft:shears 1
item replace block ^-19 ^2 ^3 container.10 with minecraft:yellow_stained_glass 12
item replace block ^-19 ^2 ^3 container.11 with minecraft:shears 1
item replace block ^-19 ^2 ^3 container.12 with minecraft:lime_stained_glass 9
item replace block ^-20 ^2 ^3 container.0 with minecraft:glass 2
item replace block ^-20 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-20 ^2 ^3 container.2 with minecraft:white_stained_glass 2
item replace block ^-20 ^2 ^3 container.3 with minecraft:shears 1
item replace block ^-20 ^2 ^3 container.4 with minecraft:orange_stained_glass 10
item replace block ^-20 ^2 ^3 container.5 with minecraft:shears 1
item replace block ^-20 ^2 ^3 container.6 with minecraft:magenta_stained_glass 19
item replace block ^-20 ^2 ^3 container.7 with minecraft:shears 1
item replace block ^-20 ^2 ^3 container.8 with minecraft:light_blue_stained_glass 10
item replace block ^-21 ^2 ^3 container.0 with minecraft:glass 17
item replace block ^-21 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-21 ^2 ^3 container.2 with minecraft:white_stained_glass 29
item replace block ^-22 ^2 ^3 container.0 with minecraft:shears 1
item replace block ^-22 ^2 ^3 container.1 with minecraft:white_stained_glass 2
item replace block ^-22 ^2 ^3 container.2 with minecraft:shears 1
item replace block ^-22 ^2 ^3 container.3 with minecraft:orange_stained_glass 14
item replace block ^-22 ^2 ^3 container.4 with minecraft:shears 1
item replace block ^-22 ^2 ^3 container.5 with minecraft:shears 1
item replace block ^-22 ^2 ^3 container.6 with minecraft:shears 1
item replace block ^-22 ^2 ^3 container.7 with minecraft:shears 1
item replace block ^-22 ^2 ^3 container.8 with minecraft:shears 1
item replace block ^-22 ^2 ^3 container.9 with minecraft:shears 1
item replace block ^-22 ^2 ^3 container.10 with minecraft:magenta_stained_glass 23
item replace block ^-23 ^2 ^3 container.0 with minecraft:glass 47
item replace block ^-24 ^2 ^3 container.0 with minecraft:glass 1
item replace block ^-24 ^2 ^3 container.1 with minecraft:shears 1
item replace block ^-24 ^2 ^3 container.2 with minecraft:white_stained_glass 45
item replace block ^-25 ^2 ^3 container.0 with minecraft:glass 47
